### ISSUE TITLE
图片没有排序

### ISSUE THREAD

**Issue by looyun** [RicterZ/nhentai#10]

**Comment by RicterZ** [comment]
web 还是下载的？
系统环境？

looyun <notifications@github.com>于2017年8月17日 周四下午9:48写道：

**Comment by looyun** [comment]
web,看了下好像是`file_list = os.listdir(doujinshi_dir)`没有排序。

**Comment by RicterZ** [comment]
嗯，周六我修一下。

looyun <notifications@github.com>于2017年8月17日 周四下午11:09写道：

**Comment by RicterZ** [comment]
推了个更新，看看解决没有？

**Comment by looyun** [comment]
好了
