### ISSUE TITLE
Using profile settings?

### ISSUE THREAD

**Issue by Luka1745** [RicterZ/nhentai#103]
Would it be possible to make the program able to access the users blacklist and other preferences such as language?

**Comment by RicterZ** [comment]
Please refer: https://nhentai.net/info/

**Comment by Luka1745** [comment]
What do you mean please refer. As ive tried writing " - " before the tag but it still shows the tags. Searching doesnt take blacklisting either??

**Comment by RicterZ** [comment]
```You can search for multiple terms at the same time, and this will return only galleries that contain both terms. For example, anal tanlines finds all galleries that contain both anal and tanlines.```

**Comment by Luka1745** [comment]
But there is no way to blacklist a tag like on the real website?

**Comment by RicterZ** [comment]
For example: nhentai --search 'chinese -chinese'

Regards,
Ricter Zheng


Luka1745 <notifications@github.com> 于2020年4月15日周三 下午9:26写道：
