### ISSUE TITLE
Error when downloading favorites

### ISSUE THREAD

**Issue by Shinymokuba** [RicterZ/nhentai#106]
I seem to be running into an issue when downloading my favorites. The error consistently happens on the 12th download as I have added new favorites and tried running the download multiple times. With that I don't think it is an issue with the id itself. I can provide you with the cookies I'm using in case you need to reproduce this.

For reference I am executing with the command line line shown below, however i have tried multiple versions with the same issue.

nhentai --favorites --format='[%a]-%i-%t' --download

The image below shows where the command fails, however there is a substantial amount of code below this.

![Capture](https://user-images.githubusercontent.com/62035769/76466708-8dabbd00-63be-11ea-91e9-233691cb2886.PNG)

**Comment by RicterZ** [comment]
Got, I'll fix it.
