### ISSUE TITLE
Japanese Title Option?

### ISSUE THREAD

**Issue by neslxzhen** [RicterZ/nhentai#107]
let the title be Japanese ?

**Comment by RicterZ** [comment]
Use '%s' - Subtitle of the doujinshi
```bash
nhentai --id xxx --format '%s'
```

**Comment by RicterZ** [comment]
I forgot only ASCII codes be allowed in the folder name.

**Comment by neslxzhen** [comment]
或許您在為本子命名的時候會想使用這個
`name=re.sub(r'(:|!|\|\*|\"|<|>|\?)*', "", name)`
一丁點拙見

Maybe you want to use this when naming the book
`name=re.sub(r'(:|!|\|\*|\"|<|>|\?)*', "", name)`
a little Suggest
