### ISSUE TITLE
Add support for updating favorites

### ISSUE THREAD

**Issue by Frain-Breeze** [RicterZ/nhentai#109]
It'd be nice to be able to, instead of having to fully re-download **all** favorites, only download new favorites. As favorites are sorted in order from newest favorite to oldest, this should not be too hard to do. Currently it will skip any doujins that are already downloaded, but it still checks the metadata of **every single** doujin in your favorites, which is not necessary. I could try to implement that, though it'd probably be a bodged solution.

**Comment by RicterZ** [comment]
Maybe you can add a option `--skip-checking-metadata` to solve this. Free fell to submit a PR ;P

**Comment by RicterZ** [comment]
You can try the latest version from dev branch.
Use `nhentai -F --download --save-download-history` to save your downloaded history.
Use `nhentai --clean-download-history` to clean downloaded history.
