### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by sharedwebsite** [RicterZ/nhentai#11]
Can someone dumb this down for me? I drag setup.py into the git and....? Nothing happens

**Comment by sharedwebsite** [comment]
git clone https://github.com/RicterZ/nhentai (ok i downloaded nhentai-0.2.7)
cd nhentai (cd......cant download nhentai? (Yep thats the problem!)
python setup.py install   (Sorry no clue what you mean)

**Comment by RicterZ** [comment]
try `sudo pip install nhentai`

**Comment by sharedwebsite** [comment]
bash: sudo: command not found

**Comment by linuxdude96** [comment]
Alright question can I bulk download files? I am talking 100+ doujin 😁

**Comment by RicterZ** [comment]
Of course, but you have to get all the doujinshi id, then
`nhentai --id 123456,67890,...`

**Comment by linuxdude96** [comment]
Yeah that's a lot work though. Anyway I can just search up tags I like and just have only the id show? Or even better allow for people to link their account and people can automatically download their favourite doujin from their accounts.

**Comment by RicterZ** [comment]
Ok, I will add the feature `Download favourite  doujin`
