### ISSUE TITLE
Search by tag and language?

### ISSUE THREAD

**Issue by Luka1745** [RicterZ/nhentai#113]
Is it not possible to search using both tags and a specified language?

**Comment by RicterZ** [comment]
Please check search tips: https://nhentai.net/info/

**Comment by RicterZ** [comment]
Yes, cause nhentai.net does not provide this kind of API. Also I can imple
this feature but I think it's not necessary.
If there are many people want this, I'll consider to add this feature.

Luka1745 <notifications@github.com> 于 2020年4月15日周三 下午5:24写道：
