### ISSUE TITLE
Add convert to pdf

### ISSUE THREAD

**Issue by Adhenrique12** [RicterZ/nhentai#120]
In can make if you want?

**Comment by Frain-Breeze** [comment]
I played around with this a bit, and it's rather easy to do using **PyPDF2** and **reportlab**. You can make it, otherwise I'll implement it.

**Comment by RicterZ** [comment]
Welcome to submit a pull request

Frain-Breeze <notifications@github.com> 于 2020年5月13日周三 下午4:47写道：
