### ISSUE TITLE
Error during Setup using Python 3.7.5

### ISSUE THREAD

**Issue by billxsand** [RicterZ/nhentai#124]
Hey when I install i get this error, 

> error: [Errno 13] Permission denied: 'c:\\python37\\lib\\site-packages\\easy-install.pth

I repaired Python 3.7.5 but still get the error. Any ideas? 

> PS Z:\programs\nhentai> python setup.py install
> running install
> running bdist_egg
> running egg_info
> writing nhentai.egg-info\PKG-INFO
> writing dependency_links to nhentai.egg-info\dependency_links.txt
> writing entry points to nhentai.egg-info\entry_points.txt
> writing requirements to nhentai.egg-info\requires.txt
> writing top-level names to nhentai.egg-info\top_level.txt
> reading manifest file 'nhentai.egg-info\SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> warning: no files found matching 'README.md'
> writing manifest file 'nhentai.egg-info\SOURCES.txt'
> installing library code to build\bdist.win-amd64\egg
> running install_lib
> running build_py
> creating build\bdist.win-amd64\egg
> creating build\bdist.win-amd64\egg\nhentai
> copying build\lib\nhentai\__init__.py -> build\bdist.win-amd64\egg\nhentai
> copying build\lib\nhentai\cmdline.py -> build\bdist.win-amd64\egg\nhentai
> copying build\lib\nhentai\command.py -> build\bdist.win-amd64\egg\nhentai
> copying build\lib\nhentai\constant.py -> build\bdist.win-amd64\egg\nhentai
> copying build\lib\nhentai\doujinshi.py -> build\bdist.win-amd64\egg\nhentai
> copying build\lib\nhentai\downloader.py -> build\bdist.win-amd64\egg\nhentai
> copying build\lib\nhentai\logger.py -> build\bdist.win-amd64\egg\nhentai
> copying build\lib\nhentai\parser.py -> build\bdist.win-amd64\egg\nhentai
> copying build\lib\nhentai\serializer.py -> build\bdist.win-amd64\egg\nhentai
> copying build\lib\nhentai\utils.py -> build\bdist.win-amd64\egg\nhentai
> creating build\bdist.win-amd64\egg\nhentai\viewer
> copying build\lib\nhentai\viewer\index.html -> build\bdist.win-amd64\egg\nhentai\viewer
> copying build\lib\nhentai\viewer\main.css -> build\bdist.win-amd64\egg\nhentai\viewer
> copying build\lib\nhentai\viewer\main.html -> build\bdist.win-amd64\egg\nhentai\viewer
> copying build\lib\nhentai\viewer\main.js -> build\bdist.win-amd64\egg\nhentai\viewer
> copying build\lib\nhentai\viewer\scripts.js -> build\bdist.win-amd64\egg\nhentai\viewer
> copying build\lib\nhentai\viewer\styles.css -> build\bdist.win-amd64\egg\nhentai\viewer
> byte-compiling build\bdist.win-amd64\egg\nhentai\__init__.py to __init__.cpython-37.pyc
> byte-compiling build\bdist.win-amd64\egg\nhentai\cmdline.py to cmdline.cpython-37.pyc
> byte-compiling build\bdist.win-amd64\egg\nhentai\command.py to command.cpython-37.pyc
> byte-compiling build\bdist.win-amd64\egg\nhentai\constant.py to constant.cpython-37.pyc
> byte-compiling build\bdist.win-amd64\egg\nhentai\doujinshi.py to doujinshi.cpython-37.pyc
> byte-compiling build\bdist.win-amd64\egg\nhentai\downloader.py to downloader.cpython-37.pyc
> byte-compiling build\bdist.win-amd64\egg\nhentai\logger.py to logger.cpython-37.pyc
> byte-compiling build\bdist.win-amd64\egg\nhentai\parser.py to parser.cpython-37.pyc
> byte-compiling build\bdist.win-amd64\egg\nhentai\serializer.py to serializer.cpython-37.pyc
> byte-compiling build\bdist.win-amd64\egg\nhentai\utils.py to utils.cpython-37.pyc
> creating build\bdist.win-amd64\egg\EGG-INFO
> copying nhentai.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
> copying nhentai.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
> copying nhentai.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
> copying nhentai.egg-info\entry_points.txt -> build\bdist.win-amd64\egg\EGG-INFO
> copying nhentai.egg-info\not-zip-safe -> build\bdist.win-amd64\egg\EGG-INFO
> copying nhentai.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
> copying nhentai.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
> creating 'dist\nhentai-0.3.9-py3.7.egg' and adding 'build\bdist.win-amd64\egg' to it
> removing 'build\bdist.win-amd64\egg' (and everything under it)
> Processing nhentai-0.3.9-py3.7.egg
> removing 'c:\python37\lib\site-packages\nhentai-0.3.9-py3.7.egg' (and everything under it)
> creating c:\python37\lib\site-packages\nhentai-0.3.9-py3.7.egg
> Extracting nhentai-0.3.9-py3.7.egg to c:\python37\lib\site-packages
> Adding nhentai 0.3.9 to easy-install.pth file
> error: [Errno 13] Permission denied: 'c:\\python37\\lib\\site-packages\\easy-install.pth'

**Comment by RicterZ** [comment]
try run cmd.exe as administrator and install again

billxsand <notifications@github.com> 于 2020年5月22日周五 下午12:22写道：

**Comment by billxsand** [comment]
I'm sorry I should have included that I am running as admin. 

I have tried (Admin) CMD.exe and (Admin) Powershell, both give the same error upon install

**Comment by PiPerson7472** [comment]
Try going into Z:\programs\nhentai and opening powershell with alt+f, alt+s, alt+a, then running the command
python Z:\programs\nhentai\setup.py install
I had that issue too and thats what fixed it for me.

**Comment by billxsand** [comment]
>opening powershell with alt+f, alt+s, alt+a,

What exactly do you mean by that ?

**Comment by PiPerson7472** [comment]
It opens a powershell admin window in that directory. For me when I ran an admin cmd or powershell window with the default path it gave me an error.

**Comment by billxsand** [comment]
> 
> 
> It opens a powershell admin window in that directory. For me when I ran an admin cmd or powershell window with the default path it gave me an error. And it will download everything in that directory so you can use it as a portable

What I meant was, how do I do that? Like what exactly are you telling me to do?

**Comment by billxsand** [comment]
Am I using the wrong python version perhaps? What is the recommended version
