### ISSUE TITLE
Max page command does not download all pages

### ISSUE THREAD

**Issue by PiPerson7472** [RicterZ/nhentai#125]
I read a previous issue with a language issue so I downloaded the newest dev branch to use the language setting and it will only download the first 25.

nhentai --search="group" --download --max-page=1000 --threads=11 --output=F:\Nhentai

I also tried

nhentai --search="group"  --max-page=1000 --download --threads=11 --output=F:\Nhentai

And neither of these will download more than 25. Is there a way to set it to download all of the doujins instead of setting a max page?

**Comment by leluchbritansky** [comment]
Same issue

**Comment by leluchbritansky** [comment]
--page doesn't work either

**Comment by RicterZ** [comment]
`--page` has worked on latest version,
