### ISSUE TITLE
Error download

### ISSUE THREAD

**Issue by LastApril** [RicterZ/nhentai#129]
![image](https://user-images.githubusercontent.com/25956347/84143735-47c7c900-aa81-11ea-8645-d02e039897aa.png)
I can't download anything, but i can still search. idk if this happen after nhentai updating their website or something.

**Comment by Frain-Breeze** [comment]
I'm not sure how the site structure was before the new update, but it does indeed look like that's the problem

**Comment by jwfiredragon** [comment]
Yep, recent site update broke the parser. I've submitted a [pull request](https://github.com/RicterZ/nhentai/pull/130) for a fix.
