### ISSUE TITLE
Doujinshis downloaded again - save-download-history is set

### ISSUE THREAD

**Issue by Baine** [RicterZ/nhentai#132]
Greetings :)

I've set up a few aliases to fetch new additions/changed when sorting for popular.
the command line is as follows:
```bash
nhentai -D --page=$i --rm-origin-dir --sorting=popular -o /outdir/_tmp/ --no-html -C  --save-download-history -s \*
```
(with $i stemming from an encapsulating for loop, i've tried --max-page=<value> but it only fetched the first page...)

works great, except for when i rerun the above line, the doujinshis that have been processed just before get downloaded again.

~/.nhentai/history.sqlite3 exists and the table has the ID of the downloaded entries.
Is there anything wrong with my command line, or a bug indeed?

oh, forgot: I'm on dev branch, language is set to english

**Comment by RicterZ** [comment]
`--max-page` will be removed, and try use loop to download every page is a good idea.

**Comment by RicterZ** [comment]
UPDATE:use --all-page can download all from search results
