### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by bill88t** [RicterZ/nhentai#144]
Linux: Elementary os
build fetched from dev branch
output:
`
bill88t@Laptop1:~/dev$ sudo python setup.py install
running install
running bdist_egg
running egg_info
creating nhentai.egg-info
writing requirements to nhentai.egg-info/requires.txt
writing nhentai.egg-info/PKG-INFO
writing top-level names to nhentai.egg-info/top_level.txt
writing dependency_links to nhentai.egg-info/dependency_links.txt
writing entry points to nhentai.egg-info/entry_points.txt
writing manifest file 'nhentai.egg-info/SOURCES.txt'
reading manifest file 'nhentai.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README.md'
writing manifest file 'nhentai.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/nhentai
copying nhentai/downloader.py -> build/lib.linux-x86_64-2.7/nhentai
copying nhentai/constant.py -> build/lib.linux-x86_64-2.7/nhentai
copying nhentai/logger.py -> build/lib.linux-x86_64-2.7/nhentai
copying nhentai/parser.py -> build/lib.linux-x86_64-2.7/nhentai
copying nhentai/serializer.py -> build/lib.linux-x86_64-2.7/nhentai
copying nhentai/__init__.py -> build/lib.linux-x86_64-2.7/nhentai
copying nhentai/doujinshi.py -> build/lib.linux-x86_64-2.7/nhentai
copying nhentai/command.py -> build/lib.linux-x86_64-2.7/nhentai
copying nhentai/utils.py -> build/lib.linux-x86_64-2.7/nhentai
copying nhentai/cmdline.py -> build/lib.linux-x86_64-2.7/nhentai
creating build/lib.linux-x86_64-2.7/nhentai/viewer
copying nhentai/viewer/index.html -> build/lib.linux-x86_64-2.7/nhentai/viewer
copying nhentai/viewer/main.css -> build/lib.linux-x86_64-2.7/nhentai/viewer
copying nhentai/viewer/main.html -> build/lib.linux-x86_64-2.7/nhentai/viewer
copying nhentai/viewer/main.js -> build/lib.linux-x86_64-2.7/nhentai/viewer
copying nhentai/viewer/scripts.js -> build/lib.linux-x86_64-2.7/nhentai/viewer
copying nhentai/viewer/styles.css -> build/lib.linux-x86_64-2.7/nhentai/viewer
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/nhentai
creating build/bdist.linux-x86_64/egg/nhentai/viewer
copying build/lib.linux-x86_64-2.7/nhentai/viewer/main.html -> build/bdist.linux-x86_64/egg/nhentai/viewer
copying build/lib.linux-x86_64-2.7/nhentai/viewer/main.css -> build/bdist.linux-x86_64/egg/nhentai/viewer
copying build/lib.linux-x86_64-2.7/nhentai/viewer/styles.css -> build/bdist.linux-x86_64/egg/nhentai/viewer
copying build/lib.linux-x86_64-2.7/nhentai/viewer/main.js -> build/bdist.linux-x86_64/egg/nhentai/viewer
copying build/lib.linux-x86_64-2.7/nhentai/viewer/index.html -> build/bdist.linux-x86_64/egg/nhentai/viewer
copying build/lib.linux-x86_64-2.7/nhentai/viewer/scripts.js -> build/bdist.linux-x86_64/egg/nhentai/viewer
copying build/lib.linux-x86_64-2.7/nhentai/downloader.py -> build/bdist.linux-x86_64/egg/nhentai
copying build/lib.linux-x86_64-2.7/nhentai/constant.py -> build/bdist.linux-x86_64/egg/nhentai
copying build/lib.linux-x86_64-2.7/nhentai/logger.py -> build/bdist.linux-x86_64/egg/nhentai
copying build/lib.linux-x86_64-2.7/nhentai/parser.py -> build/bdist.linux-x86_64/egg/nhentai
copying build/lib.linux-x86_64-2.7/nhentai/serializer.py -> build/bdist.linux-x86_64/egg/nhentai
copying build/lib.linux-x86_64-2.7/nhentai/__init__.py -> build/bdist.linux-x86_64/egg/nhentai
copying build/lib.linux-x86_64-2.7/nhentai/doujinshi.py -> build/bdist.linux-x86_64/egg/nhentai
copying build/lib.linux-x86_64-2.7/nhentai/command.py -> build/bdist.linux-x86_64/egg/nhentai
copying build/lib.linux-x86_64-2.7/nhentai/utils.py -> build/bdist.linux-x86_64/egg/nhentai
copying build/lib.linux-x86_64-2.7/nhentai/cmdline.py -> build/bdist.linux-x86_64/egg/nhentai
byte-compiling build/bdist.linux-x86_64/egg/nhentai/downloader.py to downloader.pyc
byte-compiling build/bdist.linux-x86_64/egg/nhentai/constant.py to constant.pyc
byte-compiling build/bdist.linux-x86_64/egg/nhentai/logger.py to logger.pyc
byte-compiling build/bdist.linux-x86_64/egg/nhentai/parser.py to parser.pyc
byte-compiling build/bdist.linux-x86_64/egg/nhentai/serializer.py to serializer.pyc
byte-compiling build/bdist.linux-x86_64/egg/nhentai/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/nhentai/doujinshi.py to doujinshi.pyc
byte-compiling build/bdist.linux-x86_64/egg/nhentai/command.py to command.pyc
byte-compiling build/bdist.linux-x86_64/egg/nhentai/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/nhentai/cmdline.py to cmdline.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying nhentai.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying nhentai.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying nhentai.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying nhentai.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying nhentai.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying nhentai.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying nhentai.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/nhentai-0.4.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing nhentai-0.4.0-py2.7.egg
creating /usr/local/lib/python2.7/dist-packages/nhentai-0.4.0-py2.7.egg
Extracting nhentai-0.4.0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Removing nhentai 0.3.9 from easy-install.pth file
Adding nhentai 0.4.0 to easy-install.pth file
Installing nhentai script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/nhentai-0.4.0-py2.7.egg
Processing dependencies for nhentai==0.4.0
Searching for Pillow
Reading https://pypi.python.org/simple/Pillow/
Downloading https://files.pythonhosted.org/packages/ce/ef/e793f6ffe245c960c42492d0bb50f8d14e2ba223f1922a5c3c81569cec44/Pillow-7.1.2.tar.gz#sha256=a0b49960110bc6ff5fead46013bcb8825d101026d466f3a4de3476defe0fb0dd
Best match: Pillow 7.1.2
Processing Pillow-7.1.2.tar.gz
Writing /tmp/easy_install-JYnToA/Pillow-7.1.2/setup.cfg
Running Pillow-7.1.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-JYnToA/Pillow-7.1.2/egg-dist-tmp-uWUCh7
Traceback (most recent call last):
  File "setup.py", line 40, in <module>
    license='MIT',
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 437, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 679, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 726, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 771, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 774, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1057, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1069, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 698, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 724, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 909, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1177, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1163, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 44, in _execfile
    code = compile(script, filename, 'exec')
  File "/tmp/easy_install-JYnToA/Pillow-7.1.2/setup.py", line 305
    yield from self.features
             ^
SyntaxError: invalid syntax
`

**Comment by leluchbritansky** [comment]
Same issue

**Comment by SnekNOTSnake** [comment]
Have you tried installing it with python 3?

**Comment by bill88t** [comment]
bill88t@Laptop1:~/Downloads/nh/dev$ sudo python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'
bill88t@Laptop1:~/Downloads/nh/dev$

**Comment by bill88t** [comment]
sudo python3 setup.py install

Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'

**Comment by Alocks** [comment]
pip3 install nhentai

**Comment by bill88t** [comment]
umm, i'm trying to install the dev version, not the release

**Comment by Alocks** [comment]
Welp, sudo apt-get install python3-setuptools

**Comment by bill88t** [comment]
after installing python3-setuptools and installing it with python 3, it worked.
(sudo python3 setup.py install)
