### ISSUE TITLE
Handling of special characters in title

### ISSUE THREAD

**Issue by Tentrilix** [RicterZ/nhentai#148]
Expanding on Baine's and a0u5 tickets: https://github.com/RicterZ/nhentai/issues/142 and https://github.com/RicterZ/nhentai/issues/146

When a Doujin's title includes forbidden characters: < > : " / \ | ? * then the directory (and file) creation will fail.

[log.txt](https://github.com/RicterZ/nhentai/files/4975381/log.txt)

line 14: [12:18:38] [CRITICAL] [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'D:\\Backup\\D\\C\\Images\\Comics\\NH\\[321313][kousoku][[Hikari no Tomoshibi (Kousoku)] Watashi to Marisa no Bondage Life!? (Touhou Project) [Digital] [English] [MrBubbles]]'

**Comment by pri-pro** [comment]
I didn't get the error on doujin you mentioned.
see #60, I think it was fixed.

**Comment by RicterZ** [comment]
fixed
