### ISSUE TITLE
New feature request 

### ISSUE THREAD

**Issue by linuxdude96** [RicterZ/nhentai#15]
consider making a python script that would allow me to download  hentai pics from all the top image boards? I would like to use tags to lookup and download images. And want to also use tags to eliminate images from being downloaded. I also don't know if this could be done as a feature. I would be to eliminate duplicate images from being downloaded by having it cross reference already downloaded images.

**Comment by RicterZ** [comment]
So, do you wanna a command such as `nhentai --tag lolicon --download` ?

**Comment by linuxdude96** [comment]
Sorry for the late reply. I forgot all about it do to work. That kind of feature would be nice. I was thinking about something a little different. I want to be able to auto download images from image boards like https://www.gelbooru.com/ ...etc Then use existing images to downloaded to prevent duplicate images from being downloaded. I would use this a lot and would really appreciate dude. BTW What books or videos would you recommend as a starting point for learning python or other code languages?

**Comment by linuxdude96** [comment]
also that tags would be extremely nice feature on booth projects. It would just simplify everything.

**Comment by RicterZ** [comment]
On the way.

**Comment by RicterZ** [comment]
@linuxdude96 @FluffyDiscord 
Finally I implement this feature in a dirty way, but it really works. :)

**Comment by RicterZ** [comment]
nhentai --tag lolicon --download
