### ISSUE TITLE
compilation terminated.

### ISSUE THREAD

**Issue by actual123321** [RicterZ/nhentai#155]
src/qpdf/annotation.cpp:11:10: fatal error: qpdf/Constants.h: No such file or directory
 #include <qpdf/Constants.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
src/qpdf/object.cpp:11:10: fatal error: qpdf/Constants.h: No such file or directory
 #include <qpdf/Constants.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
src/qpdf/object_repr.cpp:23:10: fatal error: qpdf/Constants.h: No such file or directory
 #include <qpdf/Constants.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
src/qpdf/object_convert.cpp:17:10: fatal error: qpdf/Constants.h: No such file or directory
 #include <qpdf/Constants.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/qpdf/pikepdf.cpp:15:0:
src/qpdf/pikepdf.h:15:10: fatal error: qpdf/PointerHolder.hh: No such file or directory
 #include <qpdf/PointerHolder.hh>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/qpdf/page.cpp:14:0:
src/qpdf/pikepdf.h:15:10: fatal error: qpdf/PointerHolder.hh: No such file or directory
 #include <qpdf/PointerHolder.hh>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
src/qpdf/pipeline.cpp:10:10: fatal error: qpdf/Constants.h: No such file or directory
 #include <qpdf/Constants.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/qpdf/utils.h:11:0,
                 from src/qpdf/utils.cpp:12:
src/qpdf/pikepdf.h:15:10: fatal error: qpdf/PointerHolder.hh: No such file or directory
 #include <qpdf/PointerHolder.hh>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/qpdf/qpdf_pagelist.cpp:9:0:
src/qpdf/pikepdf.h:15:10: fatal error: qpdf/PointerHolder.hh: No such file or directory
 #include <qpdf/PointerHolder.hh>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/qpdf/qpdf.cpp:14:0:
src/qpdf/pikepdf.h:15:10: fatal error: qpdf/PointerHolder.hh: No such file or directory
 #include <qpdf/PointerHolder.hh>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
x86_64-linux-gnu-g++: error: build/temp.linux-x86_64-3.6/src/qpdf/annotation.o: No such file or directory
x86_64-linux-gnu-g++: error: build/temp.linux-x86_64-3.6/src/qpdf/object.o: No such file or directory
x86_64-linux-gnu-g++: error: build/temp.linux-x86_64-3.6/src/qpdf/object_convert.o: No such file or directory
x86_64-linux-gnu-g++: error: build/temp.linux-x86_64-3.6/src/qpdf/object_repr.o: No such file or directory
x86_64-linux-gnu-g++: error: build/temp.linux-x86_64-3.6/src/qpdf/page.o: No such file or directory
x86_64-linux-gnu-g++: error: build/temp.linux-x86_64-3.6/src/qpdf/pikepdf.o: No such file or directory
x86_64-linux-gnu-g++: error: build/temp.linux-x86_64-3.6/src/qpdf/pipeline.o: No such file or directory
x86_64-linux-gnu-g++: error: build/temp.linux-x86_64-3.6/src/qpdf/qpdf.o: No such file or directory
x86_64-linux-gnu-g++: error: build/temp.linux-x86_64-3.6/src/qpdf/qpdf_pagelist.o: No such file or directory
x86_64-linux-gnu-g++: error: build/temp.linux-x86_64-3.6/src/qpdf/utils.o: No such file or directory
error: Setup script exited with error: command 'x86_64-linux-gnu-g++' failed with exit status 1

OS:  Ubuntu 18.04 x64
python3

**Comment by RicterZ** [comment]
It's seems some problem happends while installing img2pdf. I removed the requirement so you could install nhentai successfully.
