### ISSUE TITLE
How to download all pages by tag?

### ISSUE THREAD

**Issue by leluchbritansky** [RicterZ/nhentai#158]
--page-range, --max-page doesnt work

**Comment by Nontre12** [comment]
`nhentai --search="tag: YOURTAG" -D`  
or  
`nhentai --search="tag: YOURTAG" --download`

**Comment by leluchbritansky** [comment]
> `nhentai --search="tag: YOURTAG" -D`
> or
> `nhentai --search="tag: YOURTAG" --download`

If I do this, it only downloads 1 page in the search (25 doujinshi)

**Comment by Nontre12** [comment]
@leluchbritansky try this branch i created for download all search results.
[**dev-page-range**](https://github.com/Nontre12/nhentai/tree/dev-page-range)

Use:  
`nhentai --search "working" --page-all -D`  
**to download all** search results or  
`nhentai --search "working" --page-all `  
**to only output all** the results.

Reply me if it works fine.

**Comment by RicterZ** [comment]
0.4.4 released

**Comment by leluchbritansky** [comment]
> @leluchbritansky try this branch i created for download all search results.
> [**dev-page-range**](https://github.com/Nontre12/nhentai/tree/dev-page-range)
> 
> Use:  
> 
> - `nhentai --search "working" --page-all -D`  
> 
> **to download all** search results or  
> 
> - `nhentai --search "working" --page-all `  
> 
> **to only output all** the results.
> 
> Reply me if it works fine.
> 
> **EDIT ->** _I recommend you, that don't search for doujinshis with lots of pages. (
> it's going to take a long time)_

Works fine, thanks
