### ISSUE TITLE
Running without parameters sets Proxy to ''

### ISSUE THREAD

**Issue by Nontre12** [RicterZ/nhentai#168]
When you type `nhentai` **without any parameters**, it sets Proxy setting to ''.
```
[20:43:29] [INFO] nHentai ver 0.4.5: あなたも変態。 いいね?
       _   _            _        _
 _ __ | | | | ___ _ __ | |_ __ _(_)
| '_ \| |_| |/ _ \ '_ \| __/ _` | |
| | | |  _  |  __/ | | | || (_| | |
|_| |_|_| |_|\___|_| |_|\__\__,_|_|

[20:43:29] [INFO] Proxy now set to ''.
```

**Comment by Nontre12** [comment]
#169

**Comment by squishieuwu** [comment]
How did you fix this? I get this proxy set message when I type literally anything other than the --cookie parameter.

**Comment by Nontre12** [comment]
@squishieuwu don't download the last 0.4.5 version from releases neither from pypi, this fix was pulled to the master branch.
Download from here: [0.4.5 fixed](https://github.com/RicterZ/nhentai/archive/master.zip)

**Comment by Xtroyer** [comment]
> @squishieuwu don't download the last 0.4.5 version from releases neither from pypi, this fix was pulled to the master branch.
> Download from here: [0.4.5 fixed](https://github.com/RicterZ/nhentai/archive/master.zip) 👍🏼

Hi, I had the same issue, so what do I do after downloading the files you sent? Sorry I'm new to github and coding in general.
