### ISSUE TITLE
Something wrong, maybe?

### ISSUE THREAD

**Issue by shaduwu-code** [RicterZ/nhentai#176]
Hi,

I set my cookie from the website and tried to download a doujin using the command "-D" but nothing seems to happen all I get is this: 

[08:33:00] [INFO] nHentai ver 0.4.5: あなたも変態。 いいね?
       _   _            _        _
 _ __ | | | | ___ _ __ | |_ __ _(_)
| '_ \| |_| |/ _ \ '_ \| __/ _` | |
| | | |  _  |  __/ | | | || (_| | |
|_| |_|_| |_|\___|_| |_|\__\__,_|_|

[08:33:00] [INFO] Proxy now set to ''.

and the script exit, I also tried to set a proxy but nothing changed.
Is there something I'm missing?
P.S: I'm using python 3.8.5 if this matters.

**Comment by florienzh4x** [comment]
yes, me too

**Comment by dafiulh** [comment]
I think this has been fixed on issue #168, but they haven't release a newer version yet. So for now, you can install it from source code.

**Comment by shaduwu-code** [comment]
> I think this has been fixed on #169, but they haven't release a newer version yet. So for now, you can install it from source code.

Thanks man, it worked, I think the developer account got hacked then lol.

**Comment by shaduwu-code** [comment]
> yes, me too

you can go to #169 as @dafiulh said and install the fixed version but you should uninstall the pypi version first.

**Comment by RicterZ** [comment]
0.4.6 released to fix this issue
