### ISSUE TITLE
--pdf conversion error message 

### ISSUE THREAD

**Issue by Luka1745** [RicterZ/nhentai#177]
When trying to use the img2pdf library this error message is received but only sometimes 

INFO:nhentai:Writing PDF file to path: ./[335828][yoshitora][[Ryonas Station (YOSHITORA)] FloWeR [English] [Digital]]/../[335828][yoshitora][[Ryonas Station (YOSHITORA)] FloWeR [English] [Digital]].pdf
WARNING:root:Image contains transparency which cannot be retained in PDF.
WARNING:root:img2pdf will not perform a lossy operation.
WARNING:root:You can remove the alpha channel using imagemagick:
WARNING:root:  $ convert input.png -background white -alpha remove -alpha off output.png
Traceback (most recent call last):
  File "/home/rogue/.local/bin/nhentai", line 8, in <module>
    sys.exit(main())
  File "/home/rogue/.local/lib/python3.8/site-packages/nhentai/command.py", line 95, in main
    generate_pdf(options.output_dir, doujinshi, options.rm_origin_dir)
  File "/home/rogue/.local/lib/python3.8/site-packages/nhentai/utils.py", line 221, in generate_pdf
    pdf_f.write(img2pdf.convert(full_path_list))
  File "/home/rogue/.local/lib/python3.8/site-packages/img2pdf.py", line 2032, in convert
    ) in read_images(rawdata, kwargs["colorspace"], kwargs["first_frame_only"]):
  File "/home/rogue/.local/lib/python3.8/site-packages/img2pdf.py", line 1409, in read_images
    color, ndpi, imgwidthpx, imgheightpx, rotation, iccp = get_imgmetadata(
  File "/home/rogue/.local/lib/python3.8/site-packages/img2pdf.py", line 1186, in get_imgmetadata
    raise AlphaChannelError("Refusing to work on images with alpha channel")
img2pdf.AlphaChannelError: Refusing to work on images with alpha channel

**Comment by rabitdash** [comment]
https://gitlab.mister-muffin.de/josch/img2pdf/issues/76

**Comment by rabitdash** [comment]
https://gitlab.mister-muffin.de/josch/img2pdf/issues/76

**Comment by rabitdash** [comment]
It seems that img2pdf will not solve the [problem](https://gitlab.mister-muffin.de/josch/img2pdf/issues/76) in the future.so maybe convert the picture or simply switch to other library :(

**Comment by rabitdash** [comment]
It seems that img2pdf will not fix the [feature](https://gitlab.mister-muffin.de/josch/img2pdf/issues/76) in the future, maybe you can convert images before generating PDF.

**Comment by rabitdash** [comment]
Issue #153

**Comment by RicterZ** [comment]
You can use imagemagick to convert images before generating PDFs
