### ISSUE TITLE
Call For Viewer Templates!

### ISSUE THREAD

**Issue by RicterZ** [RicterZ/nhentai#179]
According #111, nhentai now supports multi viewer templates. You can use `--template` to specific templates you want.
Of cause I need more templates, you can just create a folder contains `index.html`, `style.css`, `scripts.js` at nhentai/viewer, and send a PR to dev branch.

Example template: https://github.com/RicterZ/nhentai/blob/dev/nhentai/viewer/default/index.html

**Comment by Un1Gfn** [comment]
[typo](https://0bin.net/paste/hdUr7o8u#V4pGKjdYEOd73SQeeIvLGP+f1q3EDaNXHzbRyTIN3Ws)
