### ISSUE TITLE
[Python 3.9.x support]ERROR: Command errored out with exit status 1:

### ISSUE THREAD

**Issue by FecTu** [RicterZ/nhentai#183]
![Screenshot_1](https://user-images.githubusercontent.com/47528045/102607607-c305e800-4152-11eb-99ec-b94614d5d484.png)

**Comment by Proxymiity** [comment]
HTMLParser.unescape was removed in Python 3.9. Try this :
```
pip install --upgrade pip
pip install --upgrade setuptools
```
(or downgrade to 3.8)

**Comment by RicterZ** [comment]
Fixed by upgrade pip and setuptools
