### ISSUE TITLE
'nhentai' is not recognized as an internal or external command, operable program or batch file. 

### ISSUE THREAD

**Issue by quan-le** [RicterZ/nhentai#184]
after successfully install this program, I open cmd and type nhentai --help but it only shows 
'nhentai' is not recognized as an internal or external command, operable program, or batch file. 
![image](https://user-images.githubusercontent.com/31929073/103175236-0ff86580-489b-11eb-81f8-093a25aad875.png)

And this is the installation log
D:\Program Files (GM)\phim\Private\Nhentai_Download\nhentai>py setup.py install
running install
running bdist_egg
running egg_info
creating nhentai.egg-info
writing nhentai.egg-info\PKG-INFO
writing dependency_links to nhentai.egg-info\dependency_links.txt
writing entry points to nhentai.egg-info\entry_points.txt
writing requirements to nhentai.egg-info\requires.txt
writing top-level names to nhentai.egg-info\top_level.txt
writing manifest file 'nhentai.egg-info\SOURCES.txt'
reading manifest file 'nhentai.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README.md'
writing manifest file 'nhentai.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib
creating build\lib\nhentai
copying nhentai\cmdline.py -> build\lib\nhentai
copying nhentai\command.py -> build\lib\nhentai
copying nhentai\constant.py -> build\lib\nhentai
copying nhentai\doujinshi.py -> build\lib\nhentai
copying nhentai\downloader.py -> build\lib\nhentai
copying nhentai\logger.py -> build\lib\nhentai
copying nhentai\parser.py -> build\lib\nhentai
copying nhentai\serializer.py -> build\lib\nhentai
copying nhentai\utils.py -> build\lib\nhentai
copying nhentai\__init__.py -> build\lib\nhentai
creating build\lib\nhentai\viewer
copying nhentai\viewer\logo.png -> build\lib\nhentai\viewer
copying nhentai\viewer\main.css -> build\lib\nhentai\viewer
copying nhentai\viewer\main.html -> build\lib\nhentai\viewer
copying nhentai\viewer\main.js -> build\lib\nhentai\viewer
creating build\lib\nhentai\viewer\default
copying nhentai\viewer\default\index.html -> build\lib\nhentai\viewer\default
copying nhentai\viewer\default\scripts.js -> build\lib\nhentai\viewer\default
copying nhentai\viewer\default\styles.css -> build\lib\nhentai\viewer\default
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\nhentai
copying build\lib\nhentai\cmdline.py -> build\bdist.win-amd64\egg\nhentai
copying build\lib\nhentai\command.py -> build\bdist.win-amd64\egg\nhentai
copying build\lib\nhentai\constant.py -> build\bdist.win-amd64\egg\nhentai
copying build\lib\nhentai\doujinshi.py -> build\bdist.win-amd64\egg\nhentai
copying build\lib\nhentai\downloader.py -> build\bdist.win-amd64\egg\nhentai
copying build\lib\nhentai\logger.py -> build\bdist.win-amd64\egg\nhentai
copying build\lib\nhentai\parser.py -> build\bdist.win-amd64\egg\nhentai
copying build\lib\nhentai\serializer.py -> build\bdist.win-amd64\egg\nhentai
copying build\lib\nhentai\utils.py -> build\bdist.win-amd64\egg\nhentai
creating build\bdist.win-amd64\egg\nhentai\viewer
creating build\bdist.win-amd64\egg\nhentai\viewer\default
copying build\lib\nhentai\viewer\default\index.html -> build\bdist.win-amd64\egg\nhentai\viewer\default
copying build\lib\nhentai\viewer\default\scripts.js -> build\bdist.win-amd64\egg\nhentai\viewer\default
copying build\lib\nhentai\viewer\default\styles.css -> build\bdist.win-amd64\egg\nhentai\viewer\default
copying build\lib\nhentai\viewer\logo.png -> build\bdist.win-amd64\egg\nhentai\viewer
copying build\lib\nhentai\viewer\main.css -> build\bdist.win-amd64\egg\nhentai\viewer
copying build\lib\nhentai\viewer\main.html -> build\bdist.win-amd64\egg\nhentai\viewer
copying build\lib\nhentai\viewer\main.js -> build\bdist.win-amd64\egg\nhentai\viewer
copying build\lib\nhentai\__init__.py -> build\bdist.win-amd64\egg\nhentai
byte-compiling build\bdist.win-amd64\egg\nhentai\cmdline.py to cmdline.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\nhentai\command.py to command.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\nhentai\constant.py to constant.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\nhentai\doujinshi.py to doujinshi.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\nhentai\downloader.py to downloader.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\nhentai\logger.py to logger.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\nhentai\parser.py to parser.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\nhentai\serializer.py to serializer.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\nhentai\utils.py to utils.cpython-39.pyc
byte-compiling build\bdist.win-amd64\egg\nhentai\__init__.py to __init__.cpython-39.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying nhentai.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying nhentai.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying nhentai.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying nhentai.egg-info\entry_points.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying nhentai.egg-info\not-zip-safe -> build\bdist.win-amd64\egg\EGG-INFO
copying nhentai.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying nhentai.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
creating dist
creating 'dist\nhentai-0.4.9-py3.9.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing nhentai-0.4.9-py3.9.egg
creating c:\program files\python39\lib\site-packages\nhentai-0.4.9-py3.9.egg
Extracting nhentai-0.4.9-py3.9.egg to c:\program files\python39\lib\site-packages
Adding nhentai 0.4.9 to easy-install.pth file
Installing nhentai-script.py script to C:\Program Files\Python39\Scripts
Installing nhentai.exe script to C:\Program Files\Python39\Scripts

Installed c:\program files\python39\lib\site-packages\nhentai-0.4.9-py3.9.egg
Processing dependencies for nhentai==0.4.9
Searching for iso8601>=0.1
Reading https://pypi.org/simple/iso8601/
Downloading https://files.pythonhosted.org/packages/f5/c7/06b5938e79a09112a256f26a1ae0551b04bc6aafcb71fd7ee2390c2c54c6/iso8601-0.1.13-py2.py3-none-any.whl#sha256=694be0743e9f1535ea873bfc7bd6fb62380c62b75822761859428073a17fd39c
Best match: iso8601 0.1.13
Processing iso8601-0.1.13-py2.py3-none-any.whl
Installing iso8601-0.1.13-py2.py3-none-any.whl to c:\program files\python39\lib\site-packages
Adding iso8601 0.1.13 to easy-install.pth file

Installed c:\program files\python39\lib\site-packages\iso8601-0.1.13-py3.9.egg
Searching for future>=0.15.2
Reading https://pypi.org/simple/future/
Downloading https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz#sha256=b1bead90b70cf6ec3f0710ae53a525360fa360d306a86583adc6bf83a4db537d
Best match: future 0.18.2
Processing future-0.18.2.tar.gz
Writing C:\Users\Quan\AppData\Local\Temp\easy_install-46883gko\future-0.18.2\setup.cfg
Running future-0.18.2\setup.py -q bdist_egg --dist-dir C:\Users\Quan\AppData\Local\Temp\easy_install-46883gko\future-0.18.2\egg-dist-tmp-0co5aihc
warning: no files found matching '*.au' under directory 'tests'
warning: no files found matching '*.gif' under directory 'tests'
warning: no files found matching '*.txt' under directory 'tests'
zip_safe flag not set; analyzing archive contents...
future.backports.test.__pycache__.ssl_servers.cpython-39: module references __file__
future.backports.test.__pycache__.support.cpython-39: module references __file__
future.standard_library.__pycache__.__init__.cpython-39: module references __file__
future.standard_library.__pycache__.__init__.cpython-39: module references __path__
future.utils.__pycache__.__init__.cpython-39: module MAY be using inspect.stack
past.builtins.__pycache__.misc.cpython-39: module MAY be using inspect.stack
past.translation.__pycache__.__init__.cpython-39: module references __file__
past.translation.__pycache__.__init__.cpython-39: module references __path__
creating c:\program files\python39\lib\site-packages\future-0.18.2-py3.9.egg
Extracting future-0.18.2-py3.9.egg to c:\program files\python39\lib\site-packages
Adding future 0.18.2 to easy-install.pth file
Installing futurize-script.py script to C:\Program Files\Python39\Scripts
Installing futurize.exe script to C:\Program Files\Python39\Scripts
Installing pasteurize-script.py script to C:\Program Files\Python39\Scripts
Installing pasteurize.exe script to C:\Program Files\Python39\Scripts

Installed c:\program files\python39\lib\site-packages\future-0.18.2-py3.9.egg
Searching for tabulate>=0.7.5
Reading https://pypi.org/simple/tabulate/
Downloading https://files.pythonhosted.org/packages/c4/f4/770ae9385990f5a19a91431163d262182d3203662ea2b5739d0fcfc080f1/tabulate-0.8.7-py3-none-any.whl#sha256=ac64cb76d53b1231d364babcd72abbb16855adac7de6665122f97b593f1eb2ba
Best match: tabulate 0.8.7
Processing tabulate-0.8.7-py3-none-any.whl
Installing tabulate-0.8.7-py3-none-any.whl to c:\program files\python39\lib\site-packages
Adding tabulate 0.8.7 to easy-install.pth file
Installing tabulate-script.py script to C:\Program Files\Python39\Scripts
Installing tabulate.exe script to C:\Program Files\Python39\Scripts

Installed c:\program files\python39\lib\site-packages\tabulate-0.8.7-py3.9.egg
Searching for threadpool>=1.2.7
Reading https://pypi.org/simple/threadpool/
Downloading https://files.pythonhosted.org/packages/6a/92/483af8a4325cd72c131db4e42cc4812505667b784eb180a4fba9348c4a3c/threadpool-1.3.2-py3-none-any.whl#sha256=da4ea68ce6766b7886f4c86114df1c1eedc07484c8a33b4f737ba6f5413a12ad
Best match: threadpool 1.3.2
Processing threadpool-1.3.2-py3-none-any.whl
Installing threadpool-1.3.2-py3-none-any.whl to c:\program files\python39\lib\site-packages
Adding threadpool 1.3.2 to easy-install.pth file

Installed c:\program files\python39\lib\site-packages\threadpool-1.3.2-py3.9.egg
Searching for BeautifulSoup4>=4.0.0
Reading https://pypi.org/simple/BeautifulSoup4/
Downloading https://files.pythonhosted.org/packages/d1/41/e6495bd7d3781cee623ce23ea6ac73282a373088fcd0ddc809a047b18eae/beautifulsoup4-4.9.3-py3-none-any.whl#sha256=fff47e031e34ec82bf17e00da8f592fe7de69aeea38be00523c04623c04fb666
Best match: beautifulsoup4 4.9.3
Processing beautifulsoup4-4.9.3-py3-none-any.whl
Installing beautifulsoup4-4.9.3-py3-none-any.whl to c:\program files\python39\lib\site-packages
Adding beautifulsoup4 4.9.3 to easy-install.pth file

Installed c:\program files\python39\lib\site-packages\beautifulsoup4-4.9.3-py3.9.egg
Searching for soupsieve<2.0
Reading https://pypi.org/simple/soupsieve/
Downloading https://files.pythonhosted.org/packages/39/36/f35056eb9978a622bbcedc554993d10777e3c6ff1ca24cde53f4be9c5fc4/soupsieve-1.9.6-py2.py3-none-any.whl#sha256=feb1e937fa26a69e08436aad4a9037cd7e1d4c7212909502ba30701247ff8abd
Best match: soupsieve 1.9.6
Processing soupsieve-1.9.6-py2.py3-none-any.whl
Installing soupsieve-1.9.6-py2.py3-none-any.whl to c:\program files\python39\lib\site-packages
Adding soupsieve 1.9.6 to easy-install.pth file

Installed c:\program files\python39\lib\site-packages\soupsieve-1.9.6-py3.9.egg
Searching for requests>=2.5.0
Reading https://pypi.org/simple/requests/
Downloading https://files.pythonhosted.org/packages/29/c1/24814557f1d22c56d50280771a17307e6bf87b70727d975fd6b2ce6b014a/requests-2.25.1-py2.py3-none-any.whl#sha256=c210084e36a42ae6b9219e00e48287def368a26d03a048ddad7bfee44f75871e
Best match: requests 2.25.1
Processing requests-2.25.1-py2.py3-none-any.whl
Installing requests-2.25.1-py2.py3-none-any.whl to c:\program files\python39\lib\site-packages
Adding requests 2.25.1 to easy-install.pth file

Installed c:\program files\python39\lib\site-packages\requests-2.25.1-py3.9.egg
Searching for urllib3<1.27,>=1.21.1
Reading https://pypi.org/simple/urllib3/
Downloading https://files.pythonhosted.org/packages/f5/71/45d36a8df68f3ebb098d6861b2c017f3d094538c0fb98fa61d4dc43e69b9/urllib3-1.26.2-py2.py3-none-any.whl#sha256=d8ff90d979214d7b4f8ce956e80f4028fc6860e4431f731ea4a8c08f23f99473
Best match: urllib3 1.26.2
Processing urllib3-1.26.2-py2.py3-none-any.whl
Installing urllib3-1.26.2-py2.py3-none-any.whl to c:\program files\python39\lib\site-packages
Adding urllib3 1.26.2 to easy-install.pth file

Installed c:\program files\python39\lib\site-packages\urllib3-1.26.2-py3.9.egg
Searching for idna<3,>=2.5
Reading https://pypi.org/simple/idna/
Downloading https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl#sha256=b97d804b1e9b523befed77c48dacec60e6dcb0b5391d57af6a65a312a90648c0
Best match: idna 2.10
Processing idna-2.10-py2.py3-none-any.whl
Installing idna-2.10-py2.py3-none-any.whl to c:\program files\python39\lib\site-packages
Adding idna 2.10 to easy-install.pth file

Installed c:\program files\python39\lib\site-packages\idna-2.10-py3.9.egg
Searching for chardet<5,>=3.0.2
Reading https://pypi.org/simple/chardet/
Downloading https://files.pythonhosted.org/packages/19/c7/fa589626997dd07bd87d9269342ccb74b1720384a4d739a1872bd84fbe68/chardet-4.0.0-py2.py3-none-any.whl#sha256=f864054d66fd9118f2e67044ac8981a54775ec5b67aed0441892edb553d21da5
Best match: chardet 4.0.0
Processing chardet-4.0.0-py2.py3-none-any.whl
Installing chardet-4.0.0-py2.py3-none-any.whl to c:\program files\python39\lib\site-packages
Adding chardet 4.0.0 to easy-install.pth file
Installing chardetect-script.py script to C:\Program Files\Python39\Scripts
Installing chardetect.exe script to C:\Program Files\Python39\Scripts

Installed c:\program files\python39\lib\site-packages\chardet-4.0.0-py3.9.egg
Searching for certifi>=2017.4.17
Reading https://pypi.org/simple/certifi/
Downloading https://files.pythonhosted.org/packages/5e/a0/5f06e1e1d463903cf0c0eebeb751791119ed7a4b3737fdc9a77f1cdfb51f/certifi-2020.12.5-py2.py3-none-any.whl#sha256=719a74fb9e33b9bd44cc7f3a8d94bc35e4049deebe19ba7d8e108280cfd59830
Best match: certifi 2020.12.5
Processing certifi-2020.12.5-py2.py3-none-any.whl
Installing certifi-2020.12.5-py2.py3-none-any.whl to c:\program files\python39\lib\site-packages
Adding certifi 2020.12.5 to easy-install.pth file

Installed c:\program files\python39\lib\site-packages\certifi-2020.12.5-py3.9.egg
Finished processing dependencies for nhentai==0.4.9

**Comment by quan-le** [comment]
after trying different methods, I am able to run it but only in the location where the script and python.exe is installed which is C:\Windows\System32\cmd.exe
However, when I type nhentai outside the folder, the result is the same as the above. Hope you could find the solution

**Comment by RicterZ** [comment]
You should add 'C:\Program Files\Python39\Scripts' to your PATH environment variables.
