### ISSUE TITLE
Files saved with incorrect extension

### ISSUE THREAD

**Issue by ClawhammerLobotomy** [RicterZ/nhentai#185]
It looks like the way some galleries are formatted cause the downloader to save the files with the wrong extension.

For example, the files are named 1.png, 2.png, etc. but they are actually JPEG files on the server.

When the download happens, it is using the file's name from the URL, instead of the actual file type being downloaded.

It generally works for viewing the files, but when you try and edit them in photoshop or clip studio, the file format parser throws an error.

Example galleries with the URL using png, but files are JPEG:
268529
278592
303803

Example galleries which do have PNG file types and png extensions:
340816 (only some images. 2, 5, 20)

**Comment by RicterZ** [comment]
It is nhentai.net's issue. :(
