### ISSUE TITLE
--format '%s' is not working because of whitelist approach

### ISSUE THREAD

**Issue by atsushi-hirako** [RicterZ/nhentai#186]
the command I typed
`nhentai --id 109 --format '%s'`

expecting result
`Path './(C68) [なかよひモグダン (モグダン)] 綾波 (新世紀エヴァンゲリオン)' does not exist, creating.`

actual result
`Path './(C68) [ ()]  ()' does not exist, creating.`

reason -> whitelist approach
https://github.com/RicterZ/nhentai/blob/master/nhentai/utils.py#L241
```
valid_chars = "-_.()[] %s%s" % (string.ascii_letters, string.digits)
filename = ''.join(c for c in s if c in valid_chars)
```

if not exist security proble, please accept 2-byte charactor in japanese.
I'll write mod code and upload later.

**Comment by atsushi-hirako** [comment]
https://github.com/RicterZ/nhentai/pull/187

**Comment by RicterZ** [comment]
merged
