### ISSUE TITLE
Handling of "." in title

### ISSUE THREAD

**Issue by 2Concreazum** [RicterZ/nhentai#191]
id 341631; format [%i]%t; dev version.
Script tries to create folder with "..." but fails. Created output folder expected to be "[341631][e9] Danna no Chinko ja Kanjinai..." but the result is a folder "[341631][e9] Danna no Chinko ja Kanjinai". Then parser tries to save images into non-existent folder with leads to [WinError 3].
[log.txt](https://github.com/RicterZ/nhentai/files/5789985/log.txt)

**Comment by RicterZ** [comment]
fixed in 0.4.10
