### ISSUE TITLE
Handling "|" in the title

### ISSUE THREAD

**Issue by 2Concreazum** [RicterZ/nhentai#193]
id 257522; format [%i]%t; dev-0.4.9 (downloaded from 09.01.2021) and master-0.4.10. 
Script tries to create folder with "|" and replaces it by "\t" instead to just delete the character. 
`OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'D:\\nhpars\\[257522](C90) [Mizutofu (Suishin Tenra)] Ecchi Shinai to Nekomimi ga Torenai Byouki ni Natte   \tA si…'`
[log_master.txt](https://github.com/RicterZ/nhentai/files/5793102/log_master.txt)
[log_dev_09_01_2021.txt](https://github.com/RicterZ/nhentai/files/5793125/log_dev_09_01_2021.txt)

However, dev-0.4.9 that's been downloaded from 09.12.2020 perfectly handles this.
`[20:56:21] [WARNING] Path 'D:\nhpars\[257522](C90) [Mizutofu (Suishin Tenra)] Ecchi Shinai to Nekomimi ga Torenai Byouki ni Natte  A sick...]' does not exist, creating.`
[log_dev_09-12-2020.txt](https://github.com/RicterZ/nhentai/files/5793104/log_dev_09-12-2020.txt)

**Comment by mobrine1** [comment]
Are you using python 2.x? If not install python 3, most modules for python 2 requires more tweaking because they reached EOL

**Comment by RicterZ** [comment]
No it is a "\t" character exists in the doujinshi title.
