### ISSUE TITLE
希望能加入按热门度排序的选项

### ISSUE THREAD

**Issue by bowen628** [RicterZ/nhentai#20]
&sort=popular
谢谢!

**Comment by RicterZ** [comment]
这个排序主要是应用在什么场景呢？比如搜索，或者是直接 `--toplist --download`?

**Comment by RicterZ** [comment]
nhentai 的 tag api 好像只能用 tag id..
https://nhentai.net/api/galleries/tagged?tag_id=1&sort=popular

**Comment by RicterZ** [comment]
如果有 tag name 就好了，tag id to tag name 这种 api 有吗？

**Comment by RicterZ** [comment]
可以了
