### ISSUE TITLE
About dependencies

### ISSUE THREAD

**Issue by Un1Gfn** [RicterZ/nhentai#207]
(disclaimer - I'm a python NOOB :)

[requirements.txt](https://github.com/RicterZ/nhentai/tree/master/requirements.txt)

```
soupsieve<2.0
```

[nhentai](https://github.com/RicterZ/nhentai) *seems* to be happy w/ [soupsieve 2.2.1](https://github.com/facelessuser/soupsieve/releases/tag/2.2.1) ~on my machine~. Is there any situation where `>=2.0` does not work?\
[list of soupsieve releases](https://github.com/facelessuser/soupsieve/tags)

```
threadpool>=1.2.7
```

They kinda warn about its [obsolescence](https://pypi.org/project/threadpool) ...

[nhentai/command.py](https://github.com/RicterZ/nhentai/blob/master/nhentai/command.py#L1)

```python
#!/usr/bin/env python2.7
```

What about porting to python3?

**Comment by RicterZ** [comment]
Seems need to be updated, thanks

**Comment by RicterZ** [comment]
fixed by 592e163
