### ISSUE TITLE
Convert doujinshi_ids to avoid ignoring saved DL history

### ISSUE THREAD

**Issue by AnzoP** [RicterZ/nhentai#210]
![image](https://user-images.githubusercontent.com/39458645/114296386-bfb9b200-9add-11eb-8a0e-85f7323d23b9.png)

Similar to #171, but convert doujinshi_ids this time, since some ids are of string type.

**Comment by karamori77** [comment]
It can be fixed by changing line 72 from
`doujinshi_ids = list(set(doujinshi_ids) - set(data))` to
`doujinshi_ids = list(set(map(int, doujinshi_ids)) - set(data))`

**Comment by RicterZ** [comment]
Welcome to submit a pull request to fix it

**Comment by RicterZ** [comment]
I'm too busy these days ...orz

**Comment by karamori77** [comment]
It seems to have merged along with #208, including some other changes I made, I think.

**Comment by AnzoP** [comment]
My bad for the late reply, will close this now.
Thanks again for the help.
