### ISSUE TITLE
Add File with Metadata?

### ISSUE THREAD

**Issue by SomeRandomDude870** [RicterZ/nhentai#212]
Hi,
would it be possible to also download the Metadata of downloaded galleries?
Because some Plugins of Manga Viewers like Lanragi, Mango or Happypanda are able to read those and write them directly into the database.
Would be nice to have this.

**Comment by SomeRandomDude870** [comment]
push?

**Comment by RicterZ** [comment]
It's a little hard, because if fetching metadata of  doujin, the program need to access all the detail pages of every doujin. It's a huge work and need a long time to get all the details.
I have no intention to add this feature :(
