### ISSUE TITLE
Write downloaded Galleries to File?

### ISSUE THREAD

**Issue by SomeRandomDude870** [RicterZ/nhentai#215]
Hi,
would it possible that you add an function which writes the downloaded Galleries to an File and then when it downloads again checks if the Gallery was already downloaded?
To avoid duplicates?
Because I am often moving the folder around and I would rather not download everything a dozen times.

**Comment by RicterZ** [comment]
Seems like that nhentai already have this feature.
Check `--save-download-history` option
