### ISSUE TITLE
%t formatter getting full name instead of just doujinshi name

### ISSUE THREAD

**Issue by gauraputu** [RicterZ/nhentai#220]
an example I want to take this name

> Mitsu Shimasho

but instead, I got this when using %t

> [Bakunyu Fullnerson (Kokuryuugan)] Mitsu Shimasho [English] [biribiri] [Digital]

**Comment by RicterZ** [comment]
Fixed in new commits

**Comment by RicterZ** [comment]
Use `--format '%p'`
