### ISSUE TITLE
Possible issue fetching/storing metadata for main viewer

### ISSUE THREAD

**Issue by Amolith** [RicterZ/nhentai#227]
Earlier this evening, I downloaded ~5 pages of doujinshi matching a few specific tags. After waiting for them to download, generating the HTML viewer for each one, then regenerating the overall index, I started browsing around and noticed that there were only 3 items matching one of those tags. When I started poking around in the directories, I found that only 27 of them have a `metadata.json` file while all of them (189) have the `ComicInfo.xml` file:

```
❯ fd -t f ".json" | wc -l
27

❯ fd -t f ".xml" | wc -l
189
```

I assume the main viewer makes use of the metadata files for associating tags with certain doujinshi and that's why the search results are inaccurate. If that's the case, does anyone know why metadata wasn't fetched?

**Comment by RicterZ** [comment]
`ComicInfo.xml` only be generated if `--cbz` option be specified, but `metadata.json` will be generated for every doujinshi object, it's wired that the json file is less chan the xml file. Could you provide some doujinshi ids which have no json file but have the xml file?
