### ISSUE TITLE
Anyone else struggling to get nhentai to run?

### ISSUE THREAD

**Issue by googuzzler** [RicterZ/nhentai#229]
I installed it manually and with pip, but none of the nhentai commands work and say _"nhentai: command not found"_.

Curious if I'm doing something wrong or not.

**Comment by TravisDavis-ops** [comment]
Check your paths

**Comment by karamori77** [comment]
If you are using windows, search for 'Environment Variables' then click 'Environment Variables' at the bottom right. Then, click on 'Path' under 'User variables for {username}', click 'edit', then add a new entry 'C:\Users\{username}\AppData\Roaming\Python\{depends on ur python version}\Scripts\'. After that you should be fine.

**Comment by Nan123721** [comment]
reinstall python with a download off of the Python site, make sure to remove previous installs first, and make sure to check add python to PATH in the installer, worked for me.
