### ISSUE TITLE
nixpkg

### ISSUE THREAD

**Issue by TravisDavis-ops** [RicterZ/nhentai#230]
i have put together a nix package for this, and i wasn't sure if i needed your blessing before i start trying to get it in the repo's, thanks in advance

**Comment by RicterZ** [comment]
welcome to send PRs

**Comment by TravisDavis-ops** [comment]
https://github.com/NixOS/nixpkgs/blob/nixos-21.11/pkgs/applications/misc/nhentai/default.nix

**Comment by TravisDavis-ops** [comment]
Added install instructions for nixos to readme
