### ISSUE TITLE
Filenames truncated when title is too long, filename name format metadata gets lost

### ISSUE THREAD

**Issue by jherazob** [RicterZ/nhentai#232]
When you use a name format that includes the title, if its too long the filename ends up truncated. This is not an issue if you leave the default format of "[%i][%a][%t]", but if you change it and the title is not the last, the rest of the info gets lost. 

For organization i tried to change it to "%a-%t-%i" (the number is not helpful for filename organization, "author-title-id" is neater in my opinion, you list the files and will get them automatically sorted per author, then title, with the id at the end), but if i do that nearly always i lose the id because the title is too long, and gets truncated with a "…" character in the end.

I bet this happens with other fields that are also long but haven't tested, not sure what would be saved if you used "%t-%s" as part of the format.

Might be a good idea to truncate the fields that are too long *before* the filename is constructed, that way only that field gets lost info, and usually not too much.

**Comment by RicterZ** [comment]
Thanks for your advices and sorry for my sloooooowly reply, I'll process on it.
