### ISSUE TITLE
Can't find where it downloaded to.

### ISSUE THREAD

**Issue by pinkmorgue** [RicterZ/nhentai#233]
I've just downloaded a shit ton but can't find where the files for them are.

**Comment by pinkmorgue** [comment]
Nevermind it downloaded directly into my C: drive

**Comment by Nan123721** [comment]
close the issue once the problem is solved. Also github is not a tech support site.

**Comment by pinkmorgue** [comment]
It was an issue that I had that's what this is for right?

**Comment by Nan123721** [comment]
No, these are for issues with the code. Bugs more-like.

**Comment by pinkmorgue** [comment]
I saw other questions that were similar to mine that weren't bugs

**Comment by Nan123721** [comment]
There is one other open issue that is sort of that way, the rest are bugs.

**Comment by pinkmorgue** [comment]
counted 3 that weren't bugs but ight

**Comment by Nan123721** [comment]
It's really up to the dev/project on how to use issues with git, but with most projects tech support requests aren't to be on issues. It's not a big deal though.

**Comment by pinkmorgue** [comment]
I legit made an account to figure it out but I figured it out pretty quickly. It's not put anywhere as to the default path (at least that I could find) I still can't get the OUTPUT_DIR thing to work though.

**Comment by Nan123721** [comment]
strange. In my experience on Windows 10, it auto outputs to %path%(since that's the starting dir for shells on Windows). I usually just CD to where I need it to be and then run the command.
