### ISSUE TITLE
How to set cookie?

### ISSUE THREAD

**Issue by Criarino** [RicterZ/nhentai#245]
I want to download my favorites, so I followed the instructions in the readme file to set a cookie, but I can't find the cf_chl_2 and cf_chl_prog fields in my cookie. I've tried everything but can't seem to make it work

**Comment by Kayot** [comment]
Same, I only have cf_clearance, csrftoken, and sessionid.

**Comment by Poseid00** [comment]
> I want to download my favorites, so I followed the instructions in the readme file to set a cookie, but I can't find the cf_chl_2 and cf_chl_prog fields in my cookie. I've tried everything but can't seem to make it work

You can clear your cookies of this website from you web browser and log in to the website again then you could see these cookies, I did it but still couldn't download the comics because of the blocks of cloudflare.

**Comment by Kayot** [comment]
I cleared my cookies, but the only extra cookie I got was cf_chl_seq_c6d364a6d3b242d. Maybe I'm doing it wrong? I cleared it under Dev Tools->Application->Cookies->nHentai->right-click Clear Cookies -> Relog in.

Maybe I should try using Firefox?

**Comment by Poseid00** [comment]
> I cleared my cookies, but the only extra cookie I got was cf_chl_seq_c6d364a6d3b242d. Maybe I'm doing it wrong? I cleared it under Dev Tools->Application->Cookies->nHentai->right-click Clear Cookies -> Relog in.
> 
> Maybe I should try using Firefox?

You should clear them in the setting option of Chrome rather than in Dev Tools. You could google how to clear cookies of Chrome browser.

**Comment by Poseid00** [comment]
> 

I deleted cookies of this website in the setting option of Chrome, after deleting them and relog in the website, the cookies appeared, you could have a try.

**Comment by Kayot** [comment]
![cookies](https://user-images.githubusercontent.com/5719740/166155672-d8a973ae-23c3-4b93-a585-bbfacf67c086.png)
I deleted, closed browser, and relogged in. This is what I get.

**Comment by Poseid00** [comment]
> 

I cleared cookies on this page then
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/26107782/166155792-d05e6379-4039-4aa9-8e72-c4ed6a5d6505.png">

when you browsed this website, these cookies appeared.
<img width="757" alt="image" src="https://user-images.githubusercontent.com/26107782/166155867-4e189a03-7d3b-436c-8a0a-be33eb1605d6.png">

**Comment by Kayot** [comment]
That's so weird. I did the same
![cookies](https://user-images.githubusercontent.com/5719740/166156281-0b844fdf-4298-4116-b4b2-70556864ab37.png)

![cookies3](https://user-images.githubusercontent.com/5719740/166156389-3ebe899f-b3ba-49c5-b0d0-cd4bb063f31c.png)

And it's still not showing up. However I did manage to get the values using Postman which tells me that Chrome is hiding the cookies from me.

![cookies4](https://user-images.githubusercontent.com/5719740/166156402-cfaa0b21-fa94-463e-b27f-90a8d807b133.png)

Why would it do this?

**Comment by Poseid00** [comment]
Maybe you could try using other browsers.

**Comment by Kayot** [comment]
Heh, figured it out...

First, changing browsers didn't do squat. The cookie times out and dies too fast. I was able to capture the cookie with Postman's Interceptor debug session tool. But I still couldn't get it to work. Then I read the options and notices a new option:

--useragent

I set mine;

 nhentai --useragent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"

And now nHentai works.

**Comment by Kayot** [comment]
#246 This should solve that ticket as well, please test and confirm

**Comment by Poseid00** [comment]
> #246 This should solve that ticket as well, please test and confirm

It works for me, many thanks.

**Comment by Criarino** [comment]
thanks for the answer, but do I really need to use postman? Isn't there any other way ( at least one where I don't need to create yet another account I will never again use)?
