### ISSUE TITLE
Cloudflare Issue

### ISSUE THREAD

**Issue by Poseid00** [RicterZ/nhentai#246]
I typed my csrftoken, sessionid, cf_chl_2, cf_chl_prog and cf_clearance but still blocked by cloudflare. Does anyone has the same issue.

<img width="883" alt="image" src="https://user-images.githubusercontent.com/26107782/166140126-da7f8595-2a88-4f68-8985-ef49cc02f51c.png">

**Comment by krrr** [comment]
you must use the same IP address and useragent as when you got the cookie

**Comment by Poseid00** [comment]
Yeah, this ticket has been solved. Thank you.
