### ISSUE TITLE
multiple issues, broken install?

### ISSUE THREAD

**Issue by cpufreak** [RicterZ/nhentai#248]
hello, so, this all started with an error of "[DEBUG] Slow down and retry" to which I found this: https://github.com/RicterZ/nhentai/issues/243

however, it said to uninstall and reinstall, but for some reason I cannot seem to get it completely uninstalled?

even beyond that, I've tried a bunch of different things to set the cookie, none of which were successful.

my platform is Linux Mint if it's helpful any, let me know if I can provide any more information.

EDIT: I figured out how to do a clean reinstall, but still having trouble setting the cookie.

EDIT 2: is there a way to delete this issue and start over? now I can't even reinstall it. I'm sorry to keep poking it with a stick :(

**Comment by RicterZ** [comment]
Please refer to #246
A new version 0.4.17 fixed this problem
