### ISSUE TITLE
Configure Output DIrectory?

### ISSUE THREAD

**Issue by Looking4A** [RicterZ/nhentai#251]
Is there a way to configure the format for the output directory to automatically populate folders by the associated artist's name? I am attempting something along the lines of the following and then eventually plan on using this folder structure for a Lanraragi setup:

Output_Directory \ Doujinshi_authors'_name \ Doujinshi_id.cbz (with metadata in info.txt)

I understand we can designate an output directory using "-o", but would it be possible to also use the formatters such as %i and %a like how we would if using the "--format=" flag?

Might be a basic question and entirely possible already, but any help in the right direction would be appreciated.

**Comment by RicterZ** [comment]
Example: `nhentai --format '%i/%i/%t%t%t%t%t' --output /tmp/ --id 261100`
