### ISSUE TITLE
I am getting [DEBUG] Slow down and retry

### ISSUE THREAD

**Issue by ameer818** [RicterZ/nhentai#257]
my command was:

nhentai --id=177013 --download

**Comment by lokimagikil** [comment]
update your cookie and user agent

cookie needs csrftoken, sessionid and cf_clearance
useragent need the value from the parsed value from "google whatismybrowser"

hope it helps?

**Comment by RicterZ** [comment]
Please refer https://github.com/RicterZ/nhentai/blob/master/README.rst#usage
