### ISSUE TITLE
Not downloading more than 25 galleries

### ISSUE THREAD

**Issue by FluffyDiscord** [RicterZ/nhentai#26]
Using `search` or `tag` options does not search and queue more than 25 galleries (bound by page results). 
Using
`nhentai --tag lolicon --download`
throws an error
`[CRITICAL] No JSON object could be decoded`

**Comment by RicterZ** [comment]
Sorry I didn't noticed this issue, I'll take a look at it.

**Comment by RicterZ** [comment]
Now you can use `nhentai --tag lolicon --download --max-page 20` to specify the max page to download.
