### ISSUE TITLE
Cannot get your username, please check your cookie

### ISSUE THREAD

**Issue by Blep84** [RicterZ/nhentai#262]
Hi All

I have checked the other issues and fixes but none seem to work and I am not sure if it is me being an ID10t. 
after logging in with Chrome to get the cookie info from - https://nhentai.net/search/?q=english
![cookieinfo](https://user-images.githubusercontent.com/120303059/206894696-40b7d443-10ba-4561-8b2b-3522e1d3b900.png)

I add my useragent to my command (nhentai --cookie "csrftoken=xxx; sessionid=xxx; cf_clearance=xxx" --useragent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" ) run it and I get the cookie saved promt, I then try run a tester (nhentai --id=123855) and that is when I get the error.
![cannot get username](https://user-images.githubusercontent.com/120303059/206894865-ce3f0abc-c5e4-4b4c-8753-8b0fd1994955.png)

Am I missing anything? I did try pip install --upgrade nhentai as well but no change.

Appreciate any help, Thanks

**Comment by SandyRodgers-2017** [comment]
If your still having problems. It seems that your command is wrong. It is
`  --cookie="csrftoken=xxx;sessionid=xxx;cf_clearance=xxx" `
Also I set user agent in a separate command myself. If you are on linux, you can use my bash script.  Change below files extension to .sh and give it execute permission.  Use -h to pull up a help screen with the commands.
[nhentai_downloader.txt](https://github.com/RicterZ/nhentai/files/10300478/nhentai_downloader.txt)

**Comment by Blep84** [comment]
Thanks @SandyRodgers-2017, splitting my useragent command and correcting my cookie info sorted me out!
