### ISSUE TITLE
新增cbr检测

### ISSUE THREAD

**Issue by fengzeyan** [RicterZ/nhentai#27]
如果生成cbr的话貌似会删除所有图片文件，这样的话如果在不同关键词或者不同时刻同一个关键词会重复下载已经下载过的图片并重新生成cbr文件。 能否新增cbr检测，如果cbr文件已经存在的话就略过该本子。

**Comment by RicterZ** [comment]
cc @mentaterasmus

**Comment by RicterZ** [comment]
怎么复现？看了半天没看粗来

**Comment by RicterZ** [comment]
我懂了，他这边直接删掉cbz文件了。我加个选项默认不删掉。
