### ISSUE TITLE
Consider using XDG Base Directory Specification on Linux

### ISSUE THREAD

**Issue by PenitentMonke** [RicterZ/nhentai#299]
Both `config.json` and `history.sqlite3` are currently saved inside the same `.nhentai` directory, which is created directly under the user's home directory.

To many users, me included, [this isn't ideal](https://0x46.net/thoughts/2019/02/01/dotfile-madness/). We try to keep our $HOME clean, for as many reasons as there are people doing it. Developers can help us a lot in this regard by following the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

I'm asking that the developers of this repository consider following it as well.

I'd like to help make this change, be it by sending a PR or answering any questions to the best of my ability.

Here's some information that might be useful, from my understanding of the software and the spec:

- `config.json` should go to `$XDG_CONFIG_HOME/nhentai/` OR `$XDG_DATA_HOME/nhentai/`
  - I say **or**, because its behavior is strange for a configuration file. Some properties are changed frequently using the command line. Maybe it should be split into separate files? But that's a different discussion.
- `history.sqlite3` should go to `$XDG_DATA_HOME/nhentai/`
- This shouldn't be a disruptive change to most users if we try locations in order of priority:
  - Is `$XDG_(CONFIG/DATA)_HOME` environment set and `nhentai/filename` exists inside it? If so, use that.
  - Does `$HOME/.nhentai/filename` exist? If so, use that.
  - When no file is found, create it under the appropriate location, depending on whether XDG vars are set.
  - Users who care about XDG spec can manually move the files if needed.

I don't see how this could affect Windows users, but it should be possible to enable this behavior only on Linux, if that's a concern. I'd argue these files *don't* belong in `User\.nhentai\` on Windows either, if that's what's currently happening, but I don't know if it makes sense to increase the scope of this issue to include another OS.

See [Arch wiki - XDG Base Directory](https://wiki.archlinux.org/title/XDG_Base_Directory) for a list of how different software handle this issue. I also like [how Wezterm does it](https://wezfurlong.org/wezterm/config/files.html#configuration-files).

**Comment by RicterZ** [comment]
PRs are welcome :)
