### ISSUE TITLE
can't find '__main__' module in 'nhentai' ?

### ISSUE THREAD

**Issue by tophlock** [RicterZ/nhentai#30]
It's my first time using python in windows

I manage to install it using cmd > py setup.py install 

but now I'm stuck on download part because it's asking for __main__ module

ex.
nhentai-master>py nhentai --id=123855,123866
..AppData\Local\Programs\Python\Python37-32\python.exe: can't find '__main__' module in 'nhentai'

I tried to look on nhentai directory but only __init__ / cmdline/ command/ etc.. is in there, I can't find the  __main__ 

Does this only works on linux OS?

Edit: I also installed the .egg file on dist folder
Processing dependencies for nhentai==0.2.15
Finished processing dependencies for nhentai==0.2.15

**Comment by RicterZ** [comment]
Try `pip install nhentai` ?

**Comment by tophlock** [comment]
Thanks a lot, It worked! =)

- Kinda interesting so I'm learning python now through youtube
