### ISSUE TITLE
Executable bug not being generated and the html text wall

### ISSUE THREAD

**Issue by PedroHenriqueFonsecaMelo** [RicterZ/nhentai#305]
I'm editing this Problem because I solved my previous problem and I would like to describe the solution or what I think the solution was.

Regarding the download I used a git clone and the command " python setup.py install --user " for whatever reason this worked while "pip" and "python install . " did not. My python is installed globally and I believe it caused the installation to get confused on how to proceed or making it impossible to create the executable.

As for HTML, when downloading a work the entire "index" page was shown in the terminal; what I did was comment out line 138 of parser.py, this solved the problem and the HTML no longer appears.

**Comment by RicterZ** [comment]
Need more information, and try the latest version please
