### ISSUE TITLE
Request for new mirror scheme

### ISSUE THREAD

**Issue by Arisa43fps** [RicterZ/nhentai#314]
I would like you to add a feature so that the mirror can directly use the url without having to use a reverse proxy. 
I would like you to separate mirrors for websites and images. I tried to use mirror images by using the reverse proxy method with cloudflare workers with the source [here ](https://pixiv.cat/reverseproxy.html)and changing the `url.hostname` to `i.nhentai.net` and the `referer` to `https://nhentai.net/` I can access it and experience up to 2x faster image load.
Everyone can also make their own for free.
Here is an example of the url.
### Original
https://i.nhentai.net/galleries/2916698/4.jpg
### Mirror
https://nhpx.dwulpu.pp.ua/galleries/2916698/4.jpg
### Comparison of image load speed
![Screenshot 2024-05-13 223331](https://github.com/RicterZ/nhentai/assets/87550572/ef6e212a-369f-4a82-9263-47e714051e13)

**Comment by RicterZ** [comment]
Thanks for your advice, anyway, users can change `constant.py` to use this mirror
