### ISSUE TITLE
'nhentai' is not recognized as an internal or external command.

### ISSUE THREAD

**Issue by UVladM** [RicterZ/nhentai#315]
![Screenshot 2024-05-16 050010](https://github.com/RicterZ/nhentai/assets/94410222/86750bca-0fb7-47fe-8152-b1ad4bfb4dd2)
Problems with the pip version of the install.
Best way to fix is downgrade to version 0.4.18, then copy the py file out of path, then upgrade, and replace it

Just dealt with this tonight, still looking for better solutions as this script fails to handle the mirror.

**Comment by hanabate** [comment]
Good evening, can I ask you how you fixed that and how to downgrade please?

**Comment by ExtremeCaliber** [comment]
> Good evening, can I ask you how you fixed that and how to downgrade please?

figured out what he meant, so first you downgrade your version using `pip install nhentai==0.4.18` then navigate to where your scripts python folder is located, in my case it was "C:\Users\XXXX\AppData\Local\Programs\Python\Python312\Scripts". Copy the nhentai.exe, then upgrade your nhentai again with `pip install --upgrade nhentai`. Replace the nhentai.exe file back into the scripts folder, and now it should work, even with the gui.

**Comment by LabAviator** [comment]
> > Good evening, can I ask you how you fixed that and how to downgrade please?
> 
> figured out what he meant, so first you downgrade your version using `pip install nhentai==0.4.18` then navigate to where your scripts python folder is located, in my case it was "C:\Users\XXXX\AppData\Local\Programs\Python\Python312\Scripts". Copy the nhentai.exe, then upgrade your nhentai again with `pip install --upgrade nhentai`. Replace the nhentai.exe file back into the scripts folder, and now it should work, even with the gui.

This does not seem to fix the issue for me sadly.

**Comment by Wolf0006** [comment]
> > Good evening, can I ask you how you fixed that and how to downgrade please?
> 
> figured out what he meant, so first you downgrade your version using `pip install nhentai==0.4.18` then navigate to where your scripts python folder is located, in my case it was "C:\Users\XXXX\AppData\Local\Programs\Python\Python312\Scripts". Copy the nhentai.exe, then upgrade your nhentai again with `pip install --upgrade nhentai`. Replace the nhentai.exe file back into the scripts folder, and now it should work, even with the gui.

I followed your instuctions but accidentally deleted the nhentai.exe script. Now when I uninstall nhentai and even whole python and install it all back again, I still don't have nhentai.exe. It won't appear again. How can I get it back?
