### ISSUE TITLE
Faliure to download

### ISSUE THREAD

**Issue by paranetpatron** [RicterZ/nhentai#317]
Update: Realized the issue is that the mirror is defaulting to my local folder structure instead of the Nhentai url.

I cant figure out how to set a new mirror or why it's doing this.

**Comment by LabAviator** [comment]
> Update: Realized the issue is that the mirror is defaulting to my local folder structure instead of the Nhentai url.

How did you fix that?

**Comment by paranetpatron** [comment]
Unfortunately, I was unable to fix it. I tried uninstalling Python. I tried deleting all associated files. I tried re-downloading the nhentai-downloader. I tried about 20 hours worth of solutions.

I ended up using the Docker Hub solution instead and that seems to have to work correctly.

**Comment by LabAviator** [comment]
Ah that's a shame. I never can get Docker and its requirement to install properly, so that won't work for me.

**Comment by RicterZ** [comment]
delete .nhentai folder on your user directory will work.

- Windows: `C:\Users\[username]\.nhentai`
- MacOS: `/Users/[username]/.nhentai`
