### ISSUE TITLE
--clean-language doesnt work

### ISSUE THREAD

**Issue by ihfsa** [RicterZ/nhentai#325]
I wanted to downlaod everything i can from several specific artists but I cant clear the language and having to change the language three times for every artist is a bit annoying. Is there a workaround or anything i can do to put it back to the default?
--language=DEFAULT
--language=default
--language=all
all dont work as a solution

**Comment by ihfsa** [comment]
I found a workaround
--language=

Leave the language empty to get it to the default setting and it will download everything

**Comment by RicterZ** [comment]
Resolved, or just edit `~/.nhentai/config.json`
