### ISSUE TITLE
Error when trying to run

### ISSUE THREAD

**Issue by shinkiro25** [RicterZ/nhentai#328]
Whenever I do nhentai --id 526256 --useragent "USER AGENT of YOUR BROWSER" --cookie "XXXX" (which I replaced with the correct ones of course,
I get this error

Traceback (most recent call last):
  File "C:\Users\shini\AppData\Local\Programs\Python\Python310\Scripts\nhentai-script.py", line 33, in <module>
    sys.exit(load_entry_point('nhentai==0.5.5', 'console_scripts', 'nhentai')())
  File "C:\Users\shini\AppData\Local\Programs\Python\Python310\Scripts\nhentai-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration

Any tips on how to fix this?

**Comment by RahmanMD906** [comment]
were you able to get anything? having the same issue right now and same thing

**Comment by shinkiro25** [comment]
Sadly not

**Comment by thiendt2k1** [comment]
have you tried setting nhentai --cookie <yourcookie> andthen nhentai --useragent <yourUA> first then run it?

**Comment by m-khan** [comment]
Try the gui linked in the readme, there's some more detailed instructions in that repo's readme

**Comment by thiendt2k1** [comment]
@RahmanMD906 how about when you run nhentai --download --id 526256

**Comment by RahmanMD906** [comment]
> @RahmanMD906 how about when you run nhentai --download --id 526256

@thiendt2k1 same error

**Comment by sonoyuki** [comment]
I believe the solution to this is actually to downgrade to a different python version. Something like that, I forget exactly, but when I had a similar error with the GUI version, I punched it into chatgpt and got something like that that as a solution. In the end it did work for me. I would be more specific but I have no idea how to go back and reproduce the error now that its resolved. 
Good luck

**Comment by RahmanMD906** [comment]
> I believe the solution to this is actually to downgrade to a different python version. Something like that, I forget exactly, but when I had a similar error with the GUI version, I punched it into chatgpt and got something like that that as a solution. In the end it did work for me. I would be more specific but I have no idea how to go back and reproduce the error now that its resolved. Good luck

ayyy tysm. that worked. unistalled 3.11 and installed 3.10 and it it worked. @shinkiro25 if you still got issues maybe try this
