### ISSUE TITLE
Installation warnings and download failure

### ISSUE THREAD

**Issue by LabAviator** [RicterZ/nhentai#329]
Been trying to get this to work and have been trying to uninstall and re-install this several times in hopes of getting it to work.

But every time during installation I first get a few warnings about invalid distribution:

`C:\Windows\system32>pip install nhentai
WARNING: Ignoring invalid distribution ~ip (C:\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Python312\Lib\site-packages)
Collecting nhentai
  Using cached nhentai-0.5.3-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.11.2 in c:\python312\lib\site-packages (from nhentai) (4.12.3)
Requirement already satisfied: iso8601<2.0.0,>=1.1.0 in c:\python312\lib\site-packages (from nhentai) (1.1.0)
Requirement already satisfied: requests<3.0.0,>=2.28.2 in c:\python312\lib\site-packages (from nhentai) (2.32.3)
Requirement already satisfied: soupsieve<3.0,>=2.4 in c:\python312\lib\site-packages (from nhentai) (2.6)
Requirement already satisfied: tabulate<0.10.0,>=0.9.0 in c:\python312\lib\site-packages (from nhentai) (0.9.0)
Requirement already satisfied: urllib3<2.0.0,>=1.26.14 in c:\python312\lib\site-packages (from nhentai) (1.26.20)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\python312\lib\site-packages (from requests<3.0.0,>=2.28.2->nhentai) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\python312\lib\site-packages (from requests<3.0.0,>=2.28.2->nhentai) (3.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\python312\lib\site-packages (from requests<3.0.0,>=2.28.2->nhentai) (2024.8.30)
Using cached nhentai-0.5.3-py3-none-any.whl (42 kB)
WARNING: Ignoring invalid distribution ~ip (C:\Python312\Lib\site-packages)
Installing collected packages: nhentai
WARNING: Ignoring invalid distribution ~ip (C:\Python312\Lib\site-packages)
Successfully installed nhentai-0.5.3`

![Screenshot 2024-09-05 214121](https://github.com/user-attachments/assets/2f06db47-fa86-492f-9e27-6ae7e659e298)

And then afterwards when trying to use it with any parameters I always get this:
`'C:\Python312\Lib\site-packages\nhentai>nhentai --favorites --download --delay 1 --useragent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0" --cookie "csrftoken=hyVoCeqdoFyyTp2SK3ank14L84pFZheX9NEkqLyCmWGhkctgoFHRP7jD68yBOOcT; sessionid=h0g7f0muin1qyp6qouacur856a57enhg; cf_clearance=HlBKmaHhGusiUeiXVTGDBgleSyM2QwBVRiQY3.8pPX8-1718145295-1.0.1.1-g.krcdeLK6khHR_cwlFe2xk2YsEReV0iEPSD6HWwzE7nZtEuaIBuwZMFTk2FEyU6gX20HlEmBouvFYY8gHjvGA"
'nhentai' is not recognized as an internal or external command,
operable program or batch file.`

![Screenshot 2024-09-05 214145](https://github.com/user-attachments/assets/406b7d18-0a6f-4950-8dfe-1cf19c21837e)

**Comment by RicterZ** [comment]
add your python script directory into environment variables PATH
