### ISSUE TITLE
"#" in folder title causes issues

### ISSUE THREAD

**Issue by pmd006** [RicterZ/nhentai#330]
OS: Windows 11 Pro
Version: 23H2
OS Build: 22631.4037
Browser: Brave v1.69.162

Just came across this, don't know if its a known issue, or Windows only. I had a folder that had a octothorpe ( # ) in the folder name, and it caused issues with the folder's index.html being linked properly in the main.html file, and the image from the folder wouldn't embed either in the main.html. Clicking the space where the image should've been, my browser said the file looked like it was unavailable or had been deleted, but I checked the folder and the index.html file was there. 

Fixed it by removing the # from the folders that were having the issue and regenerating the main.html file. Now the image links just fine and the link works.

**Comment by RicterZ** [comment]
Please provide doujinshi id for reproduction

**Comment by pmd006** [comment]
528201
