### ISSUE TITLE
Local search by name, artist, tags etc.

### ISSUE THREAD

**Issue by Tim-Plaimer** [RicterZ/nhentai#333]
Is there any support for searching in my downloaded doujinshi in my download folder by name, artist, tag etc.? Or can the search function only be applied for the website?

**Comment by m-khan** [comment]
If you run --gen-main the html page it generates can be searched like that.

**Comment by JasonWS123** [comment]
If you want to browse local downloads easily, I suggest trying out Calibre. it is a very powerful tool for viewing local downloads, has powerful metadata handling, and you can even stream it to a local network or even port foward it online so you can connect to it from anywhere.

**Comment by RicterZ** [comment]
You can organize your download folder by using `--format` option, for example:

```
nhentai --id 414005 --pdf --format="%a/%i/%t"
```

The folder will be like:
```
/tmp/nihito/
└── 414005
    └── [Junnari (Nihito)] Boku to Tonari no Shojo Onee-san (29) The Virgin Onee-San (29) From Next-Door an…
        ├── 001.jpg
        ├── 002.jpg
        ├── 003.jpg
        ├── 004.jpg
        ├── 005.jpg
        ├── 006.jpg
        ├── 007.jpg
        └── 008.jpg
```
