### ISSUE TITLE
Title being cut

### ISSUE THREAD

**Issue by myussu** [RicterZ/nhentai#336]
I already have some folders created from manually downloading mirrors so i wanted to format the new downloads in a way i wouldn't create a duplicate, however it seems that when a title is too long it is being shortened followed by 3 dots at the end. I was wondering if there was a way to write the whole name without it being shortened in the folder.

**Comment by JasonWS123** [comment]
In _get_title_and_id(), you can edit this to remove the file name limiter that cuts off the title after 85th character and replaces the rest with ...
``title = title if len(title) < 85 else title[:82] + '...'``

**Comment by myussu** [comment]
sorry, its been a big while since i fiddled with code, could you tell me where is that variable? I downloaded through pip

**Comment by xifutang** [comment]
I tried deleting the line and change the number to be higher and yet no luck

**Comment by JasonWS123** [comment]
Make sure to build the codes you edit. The nhentai command is being run from the built version, NOT the primary codes you edit. You have to run ``python setup.py install`` to rebuild the project after you my changes.

**Comment by xifutang** [comment]
I mean, I've reinstalled everything even deleting Python caches & site-packages and still don't do anything. The code in the site-packages are changed to new one, yet it is still cutting the title..

Is it depends on pip version or something? (Im no programmer after all)

**Comment by myussu** [comment]
Same, i also solved it, in the utils.py i just edited the max field length to 1000, its working as i expected now, thank you.
