### ISSUE TITLE
Files

### ISSUE THREAD

**Issue by GreenTea-4u** [RicterZ/nhentai#337]
![Untitled](https://github.com/user-attachments/assets/f097edb1-823c-4c47-abf8-e473c28dfd1f)
When trying to run the command nothing happens the help list only appears in the command prompt window, how can I get this to read from the text file and start a download?

**Comment by edgar1016** [comment]
What command shows up at the start of you console log?

**Comment by RicterZ** [comment]
nhentai gui issues maybe
