### ISSUE TITLE
The values of the info.txt file generated by the --meta option are scrambled - this makes the entire file unusable

### ISSUE THREAD

**Issue by LinkZeppeli** [RicterZ/nhentai#347]
I am on version 0.5.11
Try downloading **_any_** gallery with the --meta option enabled & notice how the values of info.txt are scrambled.
For example, the gallery TAGS are in the URL: section & the gallery URL is in the TAGS: section.
Is there a fix?

**Comment by LinkZeppeli** [comment]
> Windows?

No. Arch Linux. Python 3.12.
Can you reproduce my errors?

**Comment by LinkZeppeli** [comment]
> Try [12aad84](https://github.com/RicterZ/nhentai/commit/12aad842f86764c7bb6483b2af685c17a8c7ba89) Is it worked well?

It's working perfectly now!
I assume that DATE is a new field & it was shifting everything around because it wasn't accounted for?

**Comment by RicterZ** [comment]
> > Try [12aad84](https://github.com/RicterZ/nhentai/commit/12aad842f86764c7bb6483b2af685c17a8c7ba89) Is it worked well?
> 
> It's working perfectly now! I assume that DATE is a new field & it was shifting everything around because it wasn't accounted for?

Yes, When I add the field I didn't notice that. I will release v0.5.12 to fix this

**Comment by LinkZeppeli** [comment]
@RicterZ
I just updated to the latest commit & I'm having the exact same problem again.
What went wrong this time?
Also, I haven't done any extensive testing but I feel like the downloads may be slower even though I have the same settings, network speeds, etc as before.
