### ISSUE TITLE
[CRITICAL] Tried yo get image id failed

### ISSUE THREAD

**Issue by Snubsly** [RicterZ/nhentai#350]
Hi 

I get the following error when running the below script:
PS G:\nhentai-master\nhentai-master> nhentai -o G:\test\Slime --format %p[%i] --search="tag:slime, english, -yaoi, pages:>=30" --download --page-all --sorting recent --save-download-history -t 15

Error:
[13:07:12] [INFO] Fetching doujinshi information of id 538065
[13:07:13] [CRITICAL] Tried yo get image id failed

Is there a way to have an exclusion for this failed image ID or exclude this doujinshi id to my script?
Thanks

**Comment by ym0830** [comment]
Maybe you see this error when the image format is webp instead of jpg.

**Comment by xseno123** [comment]
Noticed same with favourite download. Seem that the currently problematic one are id with 538xxx in it.
Got similar error for 538273, 538213, 538438, 538193. Tho it worked for 538063 for example

**Comment by Snubsly** [comment]
> .jpg , webp
> 
> [21:00:59] start_download: Doujinshi will be saved at "./[538213][Unknown][[Matatabi (Nanatayoshi)] Juujin sekai de Watashi ha Pet

Yeah, I  have replaced prior version with the newest version and even a fresh win install but still get the same issue.  just trying to find where I can ignore failed images so it can move to the next page

**Comment by RicterZ** [comment]
I'll make a new release

**Comment by RicterZ** [comment]
Try update to 0.5.13

**Comment by Snubsly** [comment]
Thank you, you LEGEND.
