### ISSUE TITLE
Filename ordering

### ISSUE THREAD

**Issue by nitori-dev** [RicterZ/nhentai#356]
In this commit c90c486fb4bd7b647ce2047d076f47ec8b0147b7
the filenames for pages was changed to not get zfill-ed and wasn't adjusted to do so elsewhere.
Thus the page numbers don't have extra digits.
![image](https://github.com/user-attachments/assets/c1757c37-f485-4f82-a9b1-7e3e8423c3cb)
![image](https://github.com/user-attachments/assets/bc61e76c-3c9c-4eed-a30d-2cab7d463582)
At least on my machine this screws up the ordering when generating an html viewer.

**Comment by nitori-dev** [comment]
Quick fix I did.
`diff --git a/nhentai/downloader.py b/nhentai/downloader.py
index 9bcb6f2..430e8d5 100644
--- a/nhentai/downloader.py
+++ b/nhentai/downloader.py
@@ -59,7 +59,8 @@ class Downloader(Singleton):
             await asyncio.sleep(self.delay)
 
         filename = filename if filename else os.path.basename(urlparse(url).path)
-
+        base_filename, extension = os.path.splitext(filename)
+        filename = base_filename.zfill(3) + extension
         save_file_path = os.path.join(self.folder, filename)
 
         try:`

**Comment by nitori-dev** [comment]
One possible improvement is to somehow get the length of the doujinshi and factor that into the zfill command

**Comment by nitori-dev** [comment]
Nice little solution to make sure that the filenames should always have the max amt of digits
```diff --git a/nhentai/downloader.py b/nhentai/downloader.py
index 9bcb6f2..88990be 100644
--- a/nhentai/downloader.py
+++ b/nhentai/downloader.py
@@ -4,6 +4,7 @@ import os
 import asyncio
 import httpx
 import urllib3.exceptions
+import math
 
 from urllib.parse import urlparse
 from nhentai import constant
@@ -52,14 +53,16 @@ class Downloader(Singleton):
         async with semaphore:
             return await self.download(*args, **kwargs)
 
-    async def download(self, url, folder='', filename='', retried=0, proxy=None):
+    async def download(self, url, folder='', filename='', retried=0, proxy=None, length=0):
         logger.info(f'Starting to download {url} ...')
 
         if self.delay:
             await asyncio.sleep(self.delay)
 
         filename = filename if filename else os.path.basename(urlparse(url).path)
-
+        base_filename, extension = os.path.splitext(filename)
+        digits = int(math.log10(length)) + 1
+        filename = base_filename.zfill(digits) + extension
         save_file_path = os.path.join(self.folder, filename)
 
         try:
@@ -150,7 +153,7 @@ class Downloader(Singleton):
         semaphore = asyncio.Semaphore(self.threads)
 
         coroutines = [
-            self._semaphore_download(semaphore, url, filename=os.path.basename(urlparse(url).path))
+            self._semaphore_download(semaphore, url, filename=os.path.basename(urlparse(url).path), length=len(queue))
             for url in queue
         ]

**Comment by RicterZ** [comment]
pull requests are welcome :)
