### ISSUE TITLE
Issue trying to download certain IDs

### ISSUE THREAD

**Issue by GrellOkumura** [RicterZ/nhentai#358]
I updated my version to the latest one (0.5.14) because I was having issues downloading certain IDs and saw in closed issues it was fixed in that version. The new error is a mix between IDs downloading with a lot of errors and other IDs breaking the code:

- version: 0.5.14
- command: `nhentai --id 221189 -D --format '[%a][%i] %p'`

- ID with errors: `221189`
![image](https://github.com/user-attachments/assets/87658a75-84a8-4810-9543-e54444648768)

- ID breaking the process: `538021`
![image](https://github.com/user-attachments/assets/3f9d9b28-9df1-4852-82df-2f13272587c8)

**Comment by RicterZ** [comment]
Seems it's a python version problem, a workaround is upgrade python to 3.12

**Comment by RicterZ** [comment]
0.5.15 releases, try upgrade

**Comment by GrellOkumura** [comment]
Thanks, now it works with the new version, the only problem is that the naming of the images are in disorder in the visor going 1, 10, 11... 2, 20, 21...
