### ISSUE TITLE
doujinshi_parser: Tried yo get image id failed

### ISSUE THREAD

**Issue by hahalalamummy** [RicterZ/nhentai#359]
I've downloaded newest master code and run `python setup.py install --force`

But still get error for id 538500

**Comment by RicterZ** [comment]
Cannot reproduce, pushed a workaround to skip the failed doujin

**Comment by hahalalamummy** [comment]
> Cannot reproduce, pushed a workaround to skip the failed doujin

It's still fail. And I found out that I have 2 package nhentai installed. Have to run `pip uninstall ` twice.

I think you can revert the workaround. Sorry and thank you for hard work.
