### ISSUE TITLE
The values of the info.txt file generated by the --meta option are scrambled - this makes the entire file unusable (Again)

### ISSUE THREAD

**Issue by LinkZeppeli** [RicterZ/nhentai#363]
#347
@RicterZ
I just updated to the latest commit & I'm having the exact same problem again.
What went wrong this time?
Also, I haven't done any extensive testing but I feel like the downloads may be slower even though I have the same settings, network speeds, etc as before.

**Comment by RicterZ** [comment]
try last commit, is it work as expected?
