### ISSUE TITLE
执行setup.py出错，UnicodeDecodeError

### ISSUE THREAD

**Issue by theseventhman** [RicterZ/nhentai#38]
执行setup.py出错，错误信息已经截图
![tu sl 9 2vcrp2bejlv i](https://user-images.githubusercontent.com/17475381/51021600-ff228c80-15bc-11e9-8bc9-96c1142467d7.png)

**Comment by RicterZ** [comment]
收到了，我周末看下



ricterzheng@gmail.com
 
发件人： theseventhman
发送时间： 2019-01-11 16:22
收件人： RicterZ/nhentai
抄送： Subscribed
主题： [RicterZ/nhentai] 执行setup.py出错，UnicodeDecodeError (#38)
执行setup.py出错，错误信息已经截图

**Comment by RicterZ** [comment]
@theseventhman 推荐下载最新版的 nhentai，这个问题已经解决了。
同时路径中不要含有中文，我测试了下路径中有中文的话 Python 标准库会报错

**Comment by theseventhman** [comment]
可以下载了，感谢
