### ISSUE TITLE
[CRITICAL] Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by lordkitsuna** [RicterZ/nhentai#39]
Error in the title, i started getting this just today. I am not sure what to try any id i give it it just gives me that right after fetching information on whatever i ask it to download.

**Comment by RicterZ** [comment]
Hi @lordkitsuna , please provide the command you invoked, I need it to reproduct this error

**Comment by RicterZ** [comment]
Seems nhentai.net changed them API..

**Comment by RicterZ** [comment]
![image](https://user-images.githubusercontent.com/5282759/51180312-1cc85c80-1903-11e9-8d50-3bc9c5842b72.png)

**Comment by RicterZ** [comment]
I'm working for that
