### ISSUE TITLE
nhentai API was suspended

### ISSUE THREAD

**Issue by RicterZ** [RicterZ/nhentai#40]

**Comment by RicterZ** [comment]
#39

**Comment by RicterZ** [comment]
@lordkitsuna Now it be fixed, using `pip install nhentai -U` to upgrade to 0.3.0

**Comment by lordkitsuna** [comment]
working again confirmed, thanks!

**Comment by Kadantte** [comment]
Working fine, Thank's for the Fix.

**Comment by RicterZ** [comment]
@koryphaee I'll check it

**Comment by RicterZ** [comment]
@koryphaee Sry I cannot found the API ..

**Comment by Kadantte** [comment]
@koryphaee The API is already dead fuckmaou( @nhentai ) shut it down...

**Comment by koryphaee** [comment]
I don't know if I didn't make myself clear but go to https://nhentai.net/g/1/, view source and scroll all the way to the bottom. There is a <script> tag which contains some JavaScript which contains all the API JSON.
