### ISSUE TITLE
Mirror

### ISSUE THREAD

**Issue by Kadantte** [RicterZ/nhentai#41]
Hello,
Thank's for fixing the API issues. Anyway i want to ask how can i create my own mirror for my country what i need to do that.
Thank's in advance.

**Comment by RicterZ** [comment]
You can use NGINX reverse proxy to create mirrors. Also a VPS is required.
Guide: https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/

Then you can use NGINX to reverse proxy following domains:

+ nhentai.net -> nhentai.your-mirror.com
+ i.nhentai.net -> i.nhentai.your-mirror.com

**Comment by Kadantte** [comment]
Thank's :D
