### ISSUE TITLE
issues after update 0.3.0

### ISSUE THREAD

**Issue by LastApril** [RicterZ/nhentai#42]
![image](https://user-images.githubusercontent.com/25956347/51391722-6adc9a80-1b65-11e9-8483-a68b808f76dc.png)
Sometime i can't even search or download 1 doujin or problem like in the picture, when there's no progress even i recheck my connection and there's no problem with my connection to the website.

**Comment by LastApril** [comment]
![capture](https://user-images.githubusercontent.com/25956347/51392649-4b933c80-1b68-11e9-9eca-183474a2d15c.PNG)
one in administrator mode (right) success download before and stuck after trying again, and one in left succcess with same command with the right one. uh i dont know if you understand what i'm saying... am i the only one who suffering something like this?

**Comment by RicterZ** [comment]
You mean using the administrator right can download the doujinshi successfully but the normal user cann't? I will re-product it when I using Windows.

**Comment by LastApril** [comment]
No, I mean sometimes I can download and sometime can't even with
administrator right.

**Comment by RicterZ** [comment]
I think it's maybe a connection problem. Could you access nhentai.net directly?

**Comment by LastApril** [comment]
Yes, that's why I'm asking this. I can directly read it and want to
download it, you saw it my screenshot there. If there's nothing you can fix
from my problem, you can close this issue. Hope that's my connection
problem though, thanks.

**Comment by RicterZ** [comment]
I cannot locate the problem. If it's ok, could you find the code where it's stuck. You can use `pdb`.
