### ISSUE TITLE
Suggest: set default proxy

### ISSUE THREAD

**Issue by symant233** [RicterZ/nhentai#52]
![image](https://user-images.githubusercontent.com/25316350/57173683-5a2b0880-6e66-11e9-86ab-148ec5f999e9.png)
What I'm expecting:
`nhentai --login "user:pass" --download --proxy` 
to use default `http://127.0.0.1:1080` proxy.

I'm add these codes, uninstall nhentai (by `pip uninstall nhentai`)and reinstall nhentai from edited source codes, but it won't work...
`nhentai: error: --proxy option requires 1 argument`

I don't know somewhere else check the `--proxy` arguments so I hope you can solve this.

**Comment by RicterZ** [comment]
`optparse` will check options.
```python
    parser.add_option('--proxy', type='string', dest='proxy', action='store', default='',
                      help='uses a proxy, for example: http://127.0.0.1:1080')
```

Try this code:
```python
    parser.add_option('--proxy', dest='proxy', action='store_true', default=False,
                      help='uses a proxy or not')
```
And:
```python
if args.proxy:
    constant.PROXY = {
        # your proxy here
    }
```

**Comment by symant233** [comment]
I'm considering add a config file to `~/.nhentai` which specify username, password and proxy etc.
Thanks for your help.
