### ISSUE TITLE
Timeout doesn't seem to work properly

### ISSUE THREAD

**Issue by StefanBelgica** [RicterZ/nhentai#55]
nhentai --id=177025 --timeout=1000000 --thread=1

I have tried a lot of timeout values, no matter what the download is extremely fast. I would like to leave it running for a long time and download something like one image every 10 seconds. I can't find a way to do this with the provided options.

**Comment by RicterZ** [comment]
Not a bug, you mean time interval?

**Comment by StefanBelgica** [comment]
Time interval? I don't see that option provided.

--timeout: Timeout of downloading each image

What does this option do then? Is there a way for me to set a delay between image downloads?

**Comment by RicterZ** [comment]
So.. do you want to slow down the downloading frequency?

**Comment by RicterZ** [comment]
I think this demand is a little..strange. I need a  compelling reason to add this feature.

**Comment by StefanBelgica** [comment]
Yes, because right now, even with one friend, attempting to download a lot of galleries gets me timed out by the server (usually because of the many API calls in quick succession used to find the ID of the doujins).

I fixed this myself in the code by adding a mandatory sleep in between API calls and another sleep in the block for the image requests. 

This could be added as a feature pretty easily, for now I just put in magic numbers but they can be replaced with a variable taken in as an option.

**Comment by RicterZ** [comment]
I'll add a `--delay` options between downloading two images and fetching two doujins information

**Comment by RicterZ** [comment]
nhentai 0.3.3 released, try it :)

**Comment by StefanBelgica** [comment]
`Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    long_description=long_description(),
  File "setup.py", line 15, in long_description
    return str(f.read())
  File "C:\Users\STEFAN\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 248: character maps to <undefined>`

I get this when I try to install the new version

**Comment by RicterZ** [comment]
Hi @StefanBelgica , it's a bug only on Windows / Python3, I've fixed it, reinstall via `pip install -U nhentai`

**Comment by StefanBelgica** [comment]
Works great! Thank you!
