### ISSUE TITLE
Folder name changed after nhentai update

### ISSUE THREAD

**Issue by symant233** [RicterZ/nhentai#57]
The doujinshi folder name has been changed after `nhentai`'s update.
It's good to have a more readable doujinshi name BUT new `nhentai` will ignore old doujinshis.

For example, I use `0.3.4` (not the `github/master`) release, and use `login` (old one) and download my favorites. But now I merge the latest one, the folder name has been changed, and it starts downloading the doujinshi which is already exist with another folder name. 

Can you give me the name's change style so I can rename my doujinshi folder to the newest version that `master` one can figure out?

**Comment by RicterZ** [comment]
The default (and the old version) nhentai name format is `[%i][%a][%t]`.
