### ISSUE TITLE
Downloading favourites

### ISSUE THREAD

**Issue by A1TV** [RicterZ/nhentai#59]
Is there a way to download favourites now that the --login doesn't work anymore

`--delay 1 --favorites --download`
gives `[ERROR] Can't get your number of favorited doujins. Did the login failed?`
even with the cookie set

**Comment by RicterZ** [comment]
Got, I'll check it

**Comment by symant233** [comment]
Did you tried using the `--cookie` option?

**Comment by RicterZ** [comment]
I cannot reproduct this ..
```
⋊> /m/c/U/R/P/nhentai on master ◦ python -m nhentai.command --delay 1 --favorites --download[22:37:19] [INFO] nHentai ver 0.3.4: あなたも変態。 いいね?       _   _            _        _
 _ __ | | | | ___ _ __ | |_ __ _(_)
| '_ \| |_| |/ _ \ '_ \| __/ _` | |
| | | |  _  |  __/ | | | || (_| | |
|_| |_|_| |_|\___|_| |_|\__\__,_|_|

[22:37:19] [INFO] Using mirror: https://nhentai.net
[22:37:20] [INFO] You have 196 favorites in 8 pages.
[22:37:20] [INFO] Getting doujinshi ids of page 1
[22:37:21] [INFO] Getting doujinshi ids of page 2
[22:37:21] [INFO] Getting doujinshi ids of page 3
[22:37:22] [INFO] Getting doujinshi ids of page 4
[22:37:22] [INFO] Getting doujinshi ids of page 5
[22:37:23] [INFO] Getting doujinshi ids of page 6
[22:37:23] [INFO] Getting doujinshi ids of page 7
[22:37:24] [INFO] Getting doujinshi ids of page 8
[22:37:25] [INFO] Fetching doujinshi information of id 271019
[22:37:27] [INFO] Fetching doujinshi information of id 225543
[22:37:28] [ERROR] Ctrl-C signal received. Stopping...
```

**Comment by RicterZ** [comment]
I think you set a wrong cookie. Try to login and get your cookie from here:
![image](https://user-images.githubusercontent.com/5282759/58810816-420afc80-8651-11e9-9f37-d634cf0d5eed.png)

**Comment by A1TV** [comment]
Still doesnt work.
I only have cfuid, csrftoken, sessionid in my cookie, and when i set it only the cfuid goes in the config
Im on linux and i also tried it in a windows vm also tried firefox, chromium, and google chrome

**Comment by RicterZ** [comment]
Could you send your Cookie to my email?
It's ricterzheng@gmail.com.

A1TV <notifications@github.com> 于 2019年6月5日周三 上午9:59写道：

**Comment by A1TV** [comment]
Sent

**Comment by A1TV** [comment]
ah, very sorry i didnt use the ''

thanks for your help!... and sorry for wasting your time

**Comment by RicterZ** [comment]
I will improve the documentation and add some samples


Regards,
Ricter Zheng


A1TV <notifications@github.com> 于2019年6月5日周三 上午10:45写道：

**Comment by nohex369** [comment]
I'm having the same problem but the fix doesn't work for me
I don't have any knowledge in this field so I had to figure everything out today

I've tried every combination of cookies that I could think of.  adding ' ' doesn't change anything. I've tried this in 3 browers, one of them being a fresh install of chrome.

Is there any more information you can give me about setting the cookies/logging in?

**Comment by RicterZ** [comment]
@nohex369 
https://github.com/RicterZ/nhentai/blob/master/.travis.yml#L16
try this example

**Comment by nohex369** [comment]
I saw that file and tried it already. I even tried with the entire line instead of just nhentai.
I replaced everything inside of the '' and pasted into cmd. No change. I feel like I'm missing something obvious
![cmd_2019-07-27_06-09-22](https://user-images.githubusercontent.com/53353929/61993151-7689ac00-b035-11e9-99f5-20f8e2aa59bc.png)

**Comment by RicterZ** [comment]
Do you mind send cookies to me by mail?
I'll debug and find out what's happened.

nohex369 <notifications@github.com> 于 2019年7月27日周六 下午6:15写道：

**Comment by nohex369** [comment]
Sent.

**Comment by Carrot78** [comment]
I'm also having this exact same issue. I've tried everything and I'm getting the same message when I try to download my favorites.

**Comment by RicterZ** [comment]
@nohex369 @Carrot78 
```bash
^^>>> proxychains  nhentai -F                                                             (1) 11:35:24 
ProxyChains-3.1 (http://proxychains.sf.net)
[11:35:26] [INFO] nHentai ver 0.3.5: あなたも変態。 いいね?
       _   _            _        _
 _ __ | | | | ___ _ __ | |_ __ _(_)
| '_ \| |_| |/ _ \ '_ \| __/ _` | |
| | | |  _  |  __/ | | | || (_| | |
|_| |_|_| |_|\___|_| |_|\__\__,_|_|

[11:35:26] [INFO] Using mirror: https://nhentai.net
|S-chain|-<>-127.0.0.1:1081-<><>-141.101.120.55:443-<><>-OK
[11:35:27] [INFO] Login successfully! Your username: non-ohex
[11:35:27] [WARNING] You do not specify --download option
|S-chain|-<>-127.0.0.1:1081-<><>-141.101.120.55:443-<><>-OK
[11:35:28] [INFO] You have 373 favorites in 15 pages.
[11:35:28] [INFO] Getting doujinshi ids of page 1
```

I can get username successfully, I think maybe you cannot access nhentai.net directly?

**Comment by RicterZ** [comment]
Check #73

**Comment by nohex369** [comment]
Using "" worked. Thank you
