### ISSUE TITLE
Win7下Python2.7报错

### ISSUE THREAD

**Issue by sykiewang** [RicterZ/nhentai#6]
[32m[23:07:19] [INFO] nHentai: 銇傘仾銇熴倐澶夋厠銆?銇勩亜銇?
       _   _            _        _
 _ __ | | | | ___ _ __ | |_ __ _(_)
| '_ \| |_| |/ _ \ '_ \| __/ _` | |
| | | |  _  |  __/ | | | || (_| | |
|_| |_|_| |_|\___|_| |_|\__\__,_|_|
[0m
[36m[23:07:19] [INFO] Fetching doujinshi information of id 134328[0m
C:\Python27\lib\site-packages\beautifulsoup4-4.5.1-py2.7.egg\bs4\__init__.py:181
: UserWarning: No parser was explicitly specified, so I'm using the best availab
le HTML parser for this system ("html.parser"). This usually isn't a problem, bu
t if you run this code on another system, or in a different virtual environment,
 it may use a different parser and behave differently.

The code that caused this warning is on line 9 of the file C:\Python27\Scripts\n
hentai-script.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

Traceback (most recent call last):
  File "C:\Python27\Scripts\nhentai-script.py", line 9, in <module>
    load_entry_point('nhentai==0.1.5', 'console_scripts', 'nhentai')()
  File "C:\Python27\lib\site-packages\nhentai-0.1.5-py2.7.egg\nhentai\command.py
", line 28, in main
    doujinshi_info = doujinshi_parser(id)
  File "C:\Python27\lib\site-packages\nhentai-0.1.5-py2.7.egg\nhentai\parser.py"
, line 37, in doujinshi_parser
    title = doujinshi_info.find('h1').text
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by RicterZ** [comment]
nhentai 暂时不支持 windows，这个报错好像是 nhentai 没访问成功…
你看一下 nhentai.ricterz.me 可以打开吗？

**Comment by sykiewang** [comment]
可以

**Comment by RicterZ** [comment]
对于Windows要做一些适配，等过几天我测试修改下看看。
主要是怕依赖库不支持Windows。

祥辰2011 <notifications@github.com>于2016年8月11日周四 下午10:32写道：

**Comment by sykiewang** [comment]
关闭Issue

**Comment by RicterZ** [comment]
Hello，现在 nhentai 0.2.2 版本支持 Windows 操作系统了
