### ISSUE TITLE
Folder name with certain characters crash

### ISSUE THREAD

**Issue by cgatlin** [RicterZ/nhentai#60]
On Widows (not sure of other OS) Folder name can not contain
\ / : * ? " <> |

downloading one with one or more of these causes a critical error.

Suggest remove these characters or changing them into a space on folder creation.

 Steps to reproduce:

> This contains a | 

`nhentai --id=253593`
> This contains a /

`nhentai --id=274301`

**Comment by RicterZ** [comment]
I added output folder name feature few days ago and forgot using `format_filename` function to standardize  output filename

**Comment by RicterZ** [comment]
Fixed in this commit: 11722823622aac8bb695a37e695fec9db7366cc9
You can use git clone this project and checkout to dev branch.
