### ISSUE TITLE
Unable to launch installation

### ISSUE THREAD

**Issue by AnonymousWeeb** [RicterZ/nhentai#63]
I'm completely new to using the command line and was having a really hard time running this due to my inexperience. I keep getting the error "FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'. I'm running on a Windows 10 computer and am generally unclear how to work the installation.

Here is my process so far:

.. code-block:: 
(Is this a command for linux only or am I just confusing myself?)

git clone https://github.com/RicterZ/nhentai 
(Downloaded this and have tried here as well https://pypi.org/project/nhentai/#description)
   
cd nhentai
(I tried writing hentai, cd nhentai etc in the command prompt with no luck)

python setup.py install
(Either get a brief popup that closes immediately or "FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt')

I appreciate anyone who decided to read this far. I know I'm coming across rather dimwitted, but if anyone could help me understand I would really appreciate it!

**Comment by A1TV** [comment]
try
pip install nhentai

**Comment by AnonymousWeeb** [comment]
Thanks for the response, I figured out that back when I first downloaded python I didn't enable PATH for the command prompt to recognize the command 'python.'

If you don't mind me asking, how might I change the path to where the folders are saved? Right now they are saving to: C:\Users\Me

If it is possible I'd really appreciate the help, thanks!

**Comment by A1TV** [comment]
`-o OUTPUT_DIR`
or cd to the folder you want to save the folders to

**Comment by AnonymousWeeb** [comment]
I am able to cd to a folder, but it will only go 1 folder deep at a time for it to work:

cd B:\Collection
cd [RAW]
nhentai --id=000000

For Reference, when I tried one long string it incorrectly displays the directory I inputted:
cd B:\Collection\[RAW]
bash: cd: B:Collection[RAW]: No such file or directory

I'd like to try inputting the directory by your first method '-o OUTPUT_DIR.' I am not inputting the command in properly right now, as it is not recognizing the commands listed on the readme file. 

Do you think you could give me an example of how you used the command with your setup, or possibly creating an example using the directories I have? Thanks for your patience, I'm starting to get more comfortable with this, but it's still pretty new territory for me.

**Comment by A1TV** [comment]
you need to 
`cd B:\Collection\[RAW]`
or
`nhentai -id=000000 -o B:\Collection\[RAW] `

**Comment by RicterZ** [comment]
Hi @AnonymousWeeb 
Could you install nhentai successfully now?
