### ISSUE TITLE
request等与网络有关的封包是否应该放到downloader.py里？

### ISSUE THREAD

**Issue by KellyHwong** [RicterZ/nhentai#64]
from nhentai.parser import request一行
parser与downloader存在互相引包的关系，这样不利于单元测试
另外request也主要属于爬虫下载的内容，更多地被downloader依赖
从代码结构来看，是否把这些东西交给downloader更好呢？
（萌新来跟大佬讨论

**Comment by symant233** [comment]
`downloader` import the `request` function not the `requests` module.
`parser` contains a session which could be used by other modules, and it do a lot parse not mainly for download (it parses doujinshi info). 
If we move this module into the `downloader`, it will be harder for unit testing. (one test only parse func now need to check download function).
So I don't think that structure would be better.

**Comment by RicterZ** [comment]
放 utils 里可能会好一点？
