### ISSUE TITLE
'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by SpaceStalin** [RicterZ/nhentai#65]
Hi. Sorry to bother you, but I've started receiving this error message when trying to use the downloader. 

![1](https://user-images.githubusercontent.com/51748930/59353519-718dc900-8d23-11e9-814f-370c37ecb020.png)

![2](https://user-images.githubusercontent.com/51748930/59353533-7a7e9a80-8d23-11e9-9615-f010416af922.png)

(When getting the caps for this, I also discovered the downloader can't find tags ("Not found anything of keyword so-and-so") and says it cannot get my favorites ("Can't get your number of favorited doujins. Did the login failed?"), even though it says it did save my cache.)

What's weird is that it was working perfectly fine until a few days ago, then it died and haven't found a way to fix it, even after scrubbing out all the folders and reinstalling I get the same error. I've pretty much given up, which is why I'm asking. Do you know what could be happening? 

Thank you for your time.

**Comment by RicterZ** [comment]
Maybe you should set your cookie again I think

**Comment by RicterZ** [comment]
![image](https://user-images.githubusercontent.com/5282759/59361630-bede5a80-8d64-11e9-9c9d-b9e79d1c9293.png)

![image](https://user-images.githubusercontent.com/5282759/59361644-c7369580-8d64-11e9-8465-e1cd2550774d.png)

I added a checker for you to check whether your cookie worked

**Comment by SpaceStalin** [comment]
Ok, it was definitely a problem with the cookie. Thank you very much!!! <3
