### ISSUE TITLE
code 404 from difference file ext between cover and content

### ISSUE THREAD

**Issue by LastApril** [RicterZ/nhentai#68]
![image](https://user-images.githubusercontent.com/25956347/60288749-153fc180-993f-11e9-90ca-a54b23292844.png)
First 9 pages successfully downloaded, and from 10 until end ext of files changed from jpg to png. Maybe it cause this problem, I'm having more than one case with same problem.
https://i.nhentai.net/galleries/1432653/10.png does exist but https://i.nhentai.net/galleries/1432653/10.jpg 404 not found.

**Comment by caiheyao** [comment]
Are you in the latest version? This problem maybe have been solved in https://github.com/RicterZ/nhentai/issues/44
