### ISSUE TITLE
下载过滤器

### ISSUE THREAD

**Issue by MangoPomelo** [RicterZ/nhentai#69]
能加一个正则过滤器么...方便滤掉外语的....

**Comment by MangoPomelo** [comment]
仔细想想好像用tag过滤更方便选择语言，能加个反选过滤器么...tag的

**Comment by MangoPomelo** [comment]
抱歉，忘记了可以“tagname1 -tagname2”的逻辑搜索方法了....

**Comment by RicterZ** [comment]
震惊，学到了，，

MangoPomelo <notifications@github.com> 于 2019年7月7日周日 上午6:01写道：
