### ISSUE TITLE
Bug in the tag parser

### ISSUE THREAD

**Issue by charlesduponpon** [RicterZ/nhentai#70]
When using --max-page, the number of result is always the same (25), even for common tags. I've identified where the bug comes from:

https://github.com/RicterZ/nhentai/blob/158b15bda85e95d068d36b87988c020d8d490be4/nhentai/parser.py#L204

the URL should be `'%s/%s/?page=%d'`. There was a `/` missing.

Also, it should be `result += _get_title_and_id(response)` not `result = _get_title_and_id(response)` otherwise we loose the old results.

**Comment by maybeRainH** [comment]
I tried, It's ok without ``/``. But yes, ``result`` has some problem. and not just ``result += _get_title_and_id(response)``  You can make a PR. Or I will if you agree

**Comment by maybeRainH** [comment]
I don't see through all the code. And as far as i know when ``--tag`` is with ``--show`` and ``--page=2``, there are some problems. so I decide not to  make a PR , but you can check my fock on ``fix70`` branch.
https://github.com/maybeRainH/nhentai/tree/fix70

**Comment by RicterZ** [comment]
fixed
