### ISSUE TITLE
Cookies: _gid & _ga

### ISSUE THREAD

**Issue by dnkzn** [RicterZ/nhentai#73]
I feel kinda stupid for asking but i can't seem to find those 2 tokens. Firefox only displays me __cfduid, csrftoken and sessionid. Appearently all 5 are needed in order to use the account with your script. 

[It looks like this for me](https://ludes.xyz/H4tvP.png)

I already read the other 2 issues regarding this topic and the travis.yml. Using the same syntax you've shown in your example but without _gid and _ga doesn't seem to work...

Sorry for the bother

**Comment by Elvecent** [comment]
@dnkzn I've had the same problem but after I tried multiple different proxy servers one clicked and it got my username right, with those three cookies.

**Comment by dnkzn** [comment]
@Elvecent I'll try it tomorrow and check if it works me aswell. It's a weird workaround tho...

Thanks!

**Comment by RicterZ** [comment]
_ga should be the Google analysis' cookie. I'll re-check cookie of nhentai
tomorrow.

dnkzn <notifications@github.com> 于 2019年7月27日周六 下午4:32写道：

**Comment by dnkzn** [comment]
Your'e right @RicterZ . _ga is from google analytics and _gid seems to be from trafficjunky. Had both of those blocked so I didn't get the cookies in the first place. But even with all 5 of them in the right order it doesn't seem to work for me.

@Elvecent This got me kind of confused. Didn't think about this yesterday but how should a proxy affect this in any way?

I guess i'll look into the code later to see how it actually resolves that --cookie string. If my syntax isn't wrong i don't know what else is.

**Comment by RicterZ** [comment]
Yeah I'll update the README and .travis.yml
