### ISSUE TITLE
Do the download results default to listing by date? Do we have the option of choosing download by "popularity"?

### ISSUE THREAD

**Issue by davidfufu** [RicterZ/nhentai#75]
For example, manually going on nhentai and searching brings you to the results listed by "date" and then you have to click "popular". So does this downloader default to the results given by "date". Is there an option to use the "popular" results?

**Comment by Waiifu** [comment]
You can manually make it sort by popularity (or create your own new parameter), by changing
```python   
response = request('get', url=constant.SEARCH_URL, params={'q': keyword, 'page': page}).content
```
to
```python
response = request('get', url=constant.SEARCH_URL, params={'q': keyword, 'page': page, 'sort': 'popular'}).content
```

In the parser.py file. Basically, just adding the sort: popular parameter. Mind you, you need to reinstall (run setup.py) after changing this.

**Comment by RicterZ** [comment]
@Waiifu Welcome to submit a PR

**Comment by Waiifu** [comment]
@RicterZ @davidfufu Did a PR for it. https://github.com/RicterZ/nhentai/pull/79

**Comment by davidfufu** [comment]
I think he means pull request.

**Comment by RicterZ** [comment]
Merged
