### ISSUE TITLE
Issue when trying to download more than 77 favorites 

### ISSUE THREAD

**Issue by Carrot78** [RicterZ/nhentai#78]
I'm trying to download my favorites list, but every time I reach 77 doujin downloaded I get the following error and the program stops: 
![image](https://user-images.githubusercontent.com/53384792/62023034-db531c80-b183-11e9-86d9-dd0d2a8b1433.png)
I've tried multiple times and still get the same error. It doesn't seem to matter what the 77th doujin is, that's the one it always gets hung up on.

**Comment by RicterZ** [comment]
Maybe the threadpoll is full, I'll work on it.

**Comment by RicterZ** [comment]
Hi @Carrot78, try new version from dev branch, but i'm not sure it's worked fine or not...;(

**Comment by Carrot78** [comment]
Still getting the exact same issue :(

**Comment by RicterZ** [comment]
Any screenshot?


Regards,
Ricter Zheng


Carrot78 <notifications@github.com> 于2019年8月1日周四 上午7:19写道：

**Comment by RicterZ** [comment]
I wrappered the process pool as a singleton class

**Comment by RicterZ** [comment]
I have downloaded more than 114 doujinshis without any bugs :)

```bash
^^/P/nhentai >>> ls ~/Desktop/nhentai/ -1 | wc                                 (130) (dev+259) 21:07:43 
    116     116     812
```
