### ISSUE TITLE
Is there a way to print doujinshi info on a txt?

### ISSUE THREAD

**Issue by alvinzxx** [RicterZ/nhentai#80]
Hi, is there a way to create a txt file with these info below in each doujinshi folder?
            ["Doujinshi", self.name],
            ["Subtitle", self.info.subtitle],
            ["Characters", self.info.characters],
            ["Authors", self.info.artists],
            ["Languages", self.info.languages],
            ["Tags", self.info.tags],
            ["URL", self.url],
            ["Pages", self.pages],

TY

**Comment by RicterZ** [comment]
You could add this feature by yourself, check the handler function of option `--show`.
