### ISSUE TITLE
How to run program?

### ISSUE THREAD

**Issue by BetterWaifus** [RicterZ/nhentai#81]
I've successfully installed the program with python already. I am unsure how to run it.

**Comment by RicterZ** [comment]
Try to input nhentai and enter in your terminal.
It's a cli tool so that no GUI interface for you.

Also some example commands in README to help you learning how to use this
tool.

BetterWaifus <notifications@github.com> 于 2019年7月31日周三 下午11:25写道：

**Comment by BetterWaifus** [comment]
Ah, thank you.

**Comment by BetterWaifus** [comment]
Oh, where do the images save?
