### ISSUE TITLE
Feature suggestion: download tags to the html file

### ISSUE THREAD

**Issue by billxsand** [RicterZ/nhentai#87]
Hello, I am looking for a way to download the 'tag' data so that I can later sort by tags

It would be beneficial to download all the tag data (such as Parodies Tags, Artists, Languages, and Categories) from the Nhentai page, and include it somewhere in the generated HTML for easy searching 

If you view the source of any Nhentai page they are under 

```
	
	<div class="container" id="bigcontainer">
[...]
		<div id="info-block">
			<div id="info">
				<section id="tags">
```

it might be beneficial to get ALL the information such as page numbers as well

**EDIT:** just realized Another solution would be to add a 'tags' option to the 'Supported doujinshi folder formatter'

**Comment by Alocks** [comment]
In Doujinshi() Class, already indexes everything but there is no use for it yet.
There's also a push request that imports to a third party software, which should make easier imho.

Now for the html thing, the simpliest way would be using AJAX, Still I think would be better using a third party software imho. I'll look into the pull request anyways.
