### ISSUE TITLE
What cookie to use?

### ISSUE THREAD

**Issue by nicamoq** [RicterZ/nhentai#90]
Sorry for the dumb question, but regarding --cookie, what cookie exactly?

From Chrome's F12 > Application > Cookies > https://nhentai.net

-cfduid?
csrftoken?
sessionid?

![cookie](https://user-images.githubusercontent.com/27849412/68992531-9e807200-08a7-11ea-849f-5b464ac43513.png)

**Comment by RicterZ** [comment]
csrftoken and sessionid

Regards,
Ricter Zheng


Matt Rentaro <notifications@github.com> 于2019年11月16日周六 下午7:31写道：

**Comment by nicamoq** [comment]
How should the two cookies go in the --cookie command?

I tried these:
> nhentai --cookie=%CSRFTOKEN%, %SESSIONID%
> nhentai --cookie=%CSRFTOKEN% %SESSIONID%

But I always get this error:

> [19:31:44] [ERROR] Cannot get your username, please check your cookie or use `nhentai --cookie` to set your cookie

**Comment by Alocks** [comment]
Looks like it checks directly like a string, so instead **,** you need to use **;**
`nhentai --cookie csrftoken=%token%; sessionid=%id%`

**Comment by RicterZ** [comment]
https://github.com/RicterZ/nhentai/blob/master/.travis.yml#L16
