### ISSUE TITLE
Problem downloading from Favourites, error around the 50% mark of Fetching doujinshi information of id ...

### ISSUE THREAD

**Issue by manonillusts** [RicterZ/nhentai#95]
I finally figured out how to get this thing working (if someone has no idea what git is and that git program.. man it took a while) once I figured out the login/cookies, and I was happily downloading away all of my favourites with nhentai --favorites --download. I've got 413 pages and 10304 ID's, which it detects. It tracks through all the pages successfully, then begins to slowly "Fetching doujinshi information of id ######" for a long time, ie. 750/10304, giving me updates every 10.

I let this run for about two hours expecting it to be all done, but when I came back there was an error about half way through, just past the 6000th ID mark. I didn't think about making an Issue post here until I closed it... dumb of me. I'm re-doing the download now to find it again -- I tried to do nhentai --favorites --download --page=1 just to try to download the first page to see if I'd get an error, but it's checking the entire list all over again, so I'll wait to see the error and update this post.

**Comment by manonillusts** [comment]
![image](https://user-images.githubusercontent.com/34617610/70391112-853f9100-1a21-11ea-8f53-000355206e04.png)

ok i got the exact same error at i think the exact same time, so is it a problem with the nhentai doujinshi itself?

**Comment by Alocks** [comment]
The doujin parser only looks for jpg and png and the image for id 197934 is gif.

**Comment by manonillusts** [comment]
> The doujin parser only looks for jpg and png, but the image for id 197934 is gif so... 1sec to fix lol

I see there's some patch activity below this post, would I be right to think that it's fixed now? I will try again right now, either way, thanks for the quick response.

If an error like this happens again, is it as simple a fix as to temporarily un-favorite the ID causing trouble and restart the download process?

**Comment by Alocks** [comment]
`setup.py` will install _master_ branch and the push was to the _dev_ branch. 
download the dev branch [here](https://github.com/RicterZ/nhentai/archive/dev.zip), and if you're in windows, copy the **nhentai** folder to:
`%user%\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\nhentai-X.XX-pyX.X.egg\`

**Comment by manonillusts** [comment]
Mine looks like this now: 
![image](https://user-images.githubusercontent.com/34617610/70442239-d913ae00-1ae5-11ea-87ec-129aa281a701.png)

Copied only the nhentai folder from the dev branch download. I'm trying to run from this repository now with cd /c/python27/lib/site-packages/nhentai-0.3.7-py2.7.egg/nhentai then python setup.py install but it doesn't work. Uhh. This is all new stuff to me, so would I be best to just wait until this gif support change has made its way to the master branch for normal users like me doing the

git clone https://github.com/RicterZ/nhentai
cd nhentai
python setup.py install

method?

**Comment by manonillusts** [comment]
Ok, I got it to use the dev-branch's nhentai files (i put them in the place where github cloning puts the folder) and it finally managed to get through all of my favourites.

It started downloading successfully, and downloaded all 95 pages of this: /g/293149/, my most recent favourite. When it finished though, it showed a new error:

![image](https://user-images.githubusercontent.com/34617610/70459195-92cd4780-1b03-11ea-8658-7cad62a5f2df.png)

**Comment by Alocks** [comment]
looks like the code I made for metadata has no compatibility on python 2.7 lol download python 3.8 instead. I will take a look after

**Comment by manonillusts** [comment]
I uninstalled python 2.7 from my computer with CCleaner, installed Python 3.8, restarted, but now it won't setup.py install at all: 
![image](https://user-images.githubusercontent.com/34617610/70496431-74953500-1b5f-11ea-8908-fac7836b6f8c.png)
