### ISSUE TITLE
Issues in Python 2.7

### ISSUE THREAD

**Issue by Alocks** [RicterZ/nhentai#97]
-Access Denied when using --gen-main command on Windows.
-Tag splits to every character. (this issue is in parse method) 
-Python 2.7 doesn't write dictionary to json. (issue when generating metadata.json)

**Comment by symant233** [comment]
`--gen-main` utils.py line 154
```python
    try:
        data = main.format(STYLES=css, COUNT=count, PICTURE=image_html)
        if sys.version_info < (3, 0):
            with open('./main.html', 'w') as f:
                f.write(data)
        else:
            with open('./main.html', 'wb') as f:
                f.write(data.encode('utf-8'))
        logger.log(
            15, 'Main Viewer has been write to \'{0}main.html\''.format(output_dir))
    except Exception as e:
        logger.warning('Writen Main Viewer failed ({})'.format(str(e)))
```
It's a known issue that py2.7 `--gen-main` won't work. Edit should be in `if sys.version_info < (3, 0):`

**Comment by RicterZ** [comment]
removed 2.x support to solve this issue ;P
