### ISSUE TITLE
Download by Artist not available?

### ISSUE THREAD

**Issue by OmniXN** [RicterZ/nhentai#98]
The instructions for this say we can download by artist, but the option is missing in the program. Am I missing something or is the functionality not made yet?

**Comment by Alocks** [comment]
from where did you install? pip version is obsolete and been not updated long ago.
Could you print the command you're typing in bash and the message gives after it runs?

Downloading by artist is very specific, so you need to type exactly as the tag is written in nhentai website. eg.: nhentai --artist="Cle Masahiro"

**Comment by OmniXN** [comment]
Ah ok, I've installed the pip version because the regular install command wouldn't allow me to install.

**Comment by OmniXN** [comment]
I've finally figured out how to install it and run it. Thank you for letting me know about pip!
